Unique Interactsh URL
projectdiscovery/nuclei pull request #1219
Opened 2021-11-04 11:52 UTC by parrasajad

## Proposed changes

closes #1068 

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-11-04 17:39 UTC, forgedhallpass commented on v2/pkg/protocols/common/interactsh/interactsh.go
> +					matched = true
why not do the `c.interactions.Delete(id)` simply here?

2021-11-04 17:42 UTC, forgedhallpass requested changes
Please write at least one unit test that validates the changes.

2021-11-05 10:21 UTC, ehsandeep approved these changes
Tests are passing locally

2021-11-05 22:01 UTC, Ice3man543 approved these changes
lgtm!

2021-11-05 22:03 UTC, merged