Reusing dynamically extracted values as iterators in http request
projectdiscovery/nuclei pull request #1288
Opened 2021-11-24 15:42 UTC by Ice3man543

This PR adds the support in http module to iterate over the dynamically extracted data from extractors
and use it in other requests. This allows nuclei to follow links on pages, do operations with
multiple versions of the same extracted value, etc.

## Proposed changes

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2021-11-29 06:44 UTC, Ice3man543 commented
Example Template

```yaml
id: iterate-robots-request
info:
  name: Iterate robots.txt and request endpoints
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET /robots.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
      - |
        GET {{endpoint}} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
    matchers:
      - part: body
        type: word
        words:
          - "match /a"
          - "match /b"
          - "match /c"
    extractors:
      - part: body
        name: endpoint
        type: regex
        regex:
          - "(?m)/([a-zA-Z0-9-_/\\\\]+)"
        internal: true
    iterate-all: true
```

To test - 

```
 ./nuclei -t test.yaml -u https://github.com -debug
```

2021-11-29 08:22 UTC, Mzack9999 requested changes
Looks good:
- `Interactsh` test failure can be ignored
- Marking as request changes due to conflicts

2021-12-02 10:09 UTC, Mzack9999 approved these changes

2021-12-02 10:57 UTC, ehsandeep approved these changes

2021-12-02 10:57 UTC, merged