Making extractors as reusable variables
projectdiscovery/nuclei pull request #1364
Opened 2021-12-13 08:33 UTC by Mzack9999

## Proposed changes
This PR turns extractors into internal reusable variables and skip output if internal flag is set true. Check linked issue for more details.

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-12-13 14:30 UTC, ehsandeep reviewed
```yaml
id: basic-raw-example
info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /test HTTP/1.1
        Host: {{Hostname}}
        Test: {{server}}

    extractors:
      - type: kval
        name: server
        kval:
          - "server"
```

```
echo https://geonet.shodan.io | ./nuclei -t test.yaml
```

it's working as expected for the requested feature, but the base behavior of the extractor is changed, i.e the results of the extractors are not printed if matched and `internal: true` is not used.

2021-12-13 20:39 UTC, Mzack9999 commented
Setting on hold - more edge case were found and need to be tracked

cc @ehsandeep

2022-09-26 00:16 UTC, ehsandeep requested changes
merge conflict

2022-11-23 12:45 UTC, Mzack9999 commented
Outdated/Out of sync with current changes - Closing

2022-11-23 12:45 UTC, closed without merging