Replacing murmur3 with internal safe-pointer version
projectdiscovery/nuclei pull request #1444
Opened 2022-01-02 08:12 UTC by Mzack9999

## Proposed changes
This PR replaces the `murmur3` hasher with a memory-safe version.

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Notes
Other parts of the core use unsafe pointers. This may cause unexpected behaviors in the future.

2022-01-03 09:56 UTC, Ice3man543 approved these changes
lgtm!

2022-01-04 15:12 UTC, ehsandeep requested changes
```sh
$echo http://freighttableau.uber.com | nuclei -silent -t technologies/favicon-detection.yaml
[favicon-detection:tableau] [http] [info] http://freighttableau.uber.com/favicon.ico
```

```sh
$echo http://freighttableau.uber.com | ./nuclei -silent -t technologies/favicon-detection.yaml
```

looks like the calculated hash is not same as before?

2022-01-04 17:47 UTC, ehsandeep approved these changes

2022-01-04 23:28 UTC, LuitelSamikshya approved these changes

2022-01-05 06:21 UTC, merged