Add support to run remote template
projectdiscovery/nuclei pull request #1472
Opened 2022-01-12 13:06 UTC by parrasajad

* Add remote-template-domain config only flag to specify allowed domain list to load remote templates from

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-01-16 12:04 UTC, ehsandeep requested changes
Requires `go mod` update to fetch changes from goflags

2022-01-17 10:02 UTC, forgedhallpass requested changes
Since this is a sensitive feature that can lead to potential vulnerabilities if not implemented correctly, it is important to have extensive tests with multiple scenarios, especially negative.

2022-01-24 08:21 UTC, forgedhallpass requested changes

2022-01-24 08:21 UTC, forgedhallpass commented on v2/pkg/catalog/loader/remote_loader.go
> +		parsed, err := url.Parse(URL)
please state exactly what a variable holds. It's a `parsedURL`, not simply just "parsed"

2022-01-24 08:21 UTC, forgedhallpass commented on v2/pkg/catalog/loader/remote_loader.go
> +func getRemoteContent(URL string, remoteTemplateDomainList []string, w chan<- RemoteContentError, contentType ContentType) {
Please rename the `w` to something more meaningful

2022-01-24 08:21 UTC, forgedhallpass commented on v2/pkg/templates/compile.go
> +func readFromTemplatePath(templatePath string) (data []byte, err error) {
this method seems to be duplicated...please extract and reuse

2022-01-24 11:19 UTC, forgedhallpass approved these changes

2022-01-25 12:42 UTC, ehsandeep requested changes
Currently `RemoteTemplateDomainList` validation cheks only when loading single remote template with YAML extension and not when loading remote template with list input, we need to enforce the validation for 2nd input as well.

2022-01-27 12:32 UTC, ehsandeep approved these changes

2022-01-27 12:32 UTC, merged