update validation logic to validate workflow templates and subtemplates
projectdiscovery/nuclei pull request #1489
Opened 2022-01-14 11:00 UTC by parrasajad

## Proposed changes
The PR implements validation logic for templates/subtemplates within a workflow.

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-01-14 23:44 UTC, Mzack9999 requested changes

2022-01-14 23:44 UTC, Mzack9999 commented on v2/pkg/catalog/loader/loader.go
> +			areTemplatesValid = false
I think we can directly `return false`?

2022-01-14 23:44 UTC, Mzack9999 commented on v2/pkg/catalog/loader/loader.go
> +				areTemplatesValid = false
I think we can directly `return false`?

2022-01-14 23:44 UTC, Mzack9999 commented on v2/pkg/catalog/loader/loader.go
>  	return areTemplatesValid
If the previous comments make sense, I also think `return true` can be used?

2022-01-18 11:49 UTC, Mzack9999 approved these changes

2022-01-18 13:36 UTC, ehsandeep approved these changes

2022-01-18 15:56 UTC, merged