Added debug-req/resp support for interactsh interactions
projectdiscovery/nuclei pull request #1491
Opened 2022-01-15 00:07 UTC by Ice3man543

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-01-16 09:40 UTC, ehsandeep requested changes
Interactsh support with debug req/resp is working, `debug-resp` flag is not working for any other protocols.

2022-01-17 09:12 UTC, forgedhallpass commented on v2/pkg/protocols/common/interactsh/interactsh.go
> +			builder.WriteString(fmt.Sprintf("\n-----------\nDNS Request\n-----------\n\n%s\n\n", interaction.RawRequest))
The common parts, or at least the string template should be extracted and reused.

e.g.
```go
def debugMessage(cliOptions, headerText, interaction) {
  if c.options.DebugRequest || c.options.Debug {
    return fmt.Sprintf("\n-----------\n%s\n-----------\n\n%s\n\n", "HTTP Request", interaction.RawRequest)
  }
}
```

Same for the response.

2022-01-20 09:54 UTC, forgedhallpass approved these changes

2022-01-27 06:44 UTC, ehsandeep approved these changes

2022-01-27 06:44 UTC, merged