Added line number for file results + stats fixes
projectdiscovery/nuclei pull request #1495
Opened 2022-01-16 22:40 UTC by Ice3man543

## Proposed changes

Added line number for file templates results + fixed total calculation for file templates stats.

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-01-19 08:17 UTC, Mzack9999 requested changes
Due to the matches deduplication mechanism, the summary line information only reports the first match occurrence:
```console
$ cat logs/a.txt 
aaa
bbb
ccc
RequestDataTooBig
dddd
eeee
RequestDataTooBig
dd
RequestDataTooBig3
SuspiciousOperation
$ go run . -t file/logs/django-framework-exceptions.yaml -u logs -silent
[2022-01-19 09:09:31] [django-framework-exceptions:exception] [file] [medium] logs/a.txt [SuspiciousOperation,RequestDataTooBig] [Lines: 10,4]
```
I don't know if it's worth considering exposing all occurrences with something like:
```console
RequestDataTooBig
logs/a.txt:4
logs/a.txt:7
logs/a.txt:9
SuspiciousOperation
logs/a.txt:10
```

2022-01-26 13:48 UTC, ehsandeep requested changes
@Ice3man543 @Mzack9999 we are looking to print number based on matchers and not extractors, so we don't need to handle / map extracted data with line number instead we can simply print the line number of all match occurrence which is the case currently.

Requesting a change since the present line number logic only works with extractors and **not** with matchers.

2022-02-02 18:44 UTC, ehsandeep requested changes
<details>
<summary>Test Template</summary>

```yaml
id: django-framework-exceptions

info:
  name: Django Framework Exceptions
  description: Detects suspicious Django web application framework exceptions that could indicate exploitation attempts
  author: geeknik
  reference:
    - https://docs.djangoproject.com/en/1.11/ref/exceptions/
    - https://docs.djangoproject.com/en/1.11/topics/logging/#django-security
  severity: medium
  tags: file,logs,django

file:
  - extensions:
      - all

    matchers:
      - type: regex
        name: exception
        part: body
        regex:
          - 'SuspiciousOperation'
          - 'DisallowedHost'
          - 'DisallowedModelAdminLookup'
          - 'DisallowedModelAdminToField'
          - 'DisallowedRedirect'
          - 'InvalidSessionKey'
          - 'RequestDataTooBig'
          - 'SuspiciousFileOperation'
          - 'SuspiciousMultipartForm'
          - 'SuspiciousSession'
          - 'TooManyFieldsSent'
          - 'PermissionDenied'
```

</details>


<details>
<summary>Test Input (input.txt)</summary>

```
aaa
bbb
ccc
RequestDataTooBig
dddd
eeee
RequestDataTooBig
dd
RequestDataTooBig3
SuspiciousOperation
```

</details>

Example Run:

```console
echo input.txt | ./nuclei -t test.yaml

[django-framework-exceptions:exception] [file] [medium] input.txt [LN: 4,6,9,10]
```

<details>
<summary>JSON Output</summary>

```json
{
  "template-id":"django-framework-exceptions",
  "info":{
    "name":"Django Framework Exceptions",
    "author":[
      "geeknik"
    ],
    "tags":[
      "file",
      "logs",
      "django"
    ],
    "description":"Detects suspicious Django web application framework exceptions that could indicate exploitation attempts",
    "reference":[
      "https://docs.djangoproject.com/en/1.11/ref/exceptions/",
      "https://docs.djangoproject.com/en/1.11/topics/logging/#django-security"
    ],
    "severity":"medium"
  },
  "matcher-name":"exception",
  "type":"file",
  "path":"input.txt",
  "matched-at":"input.txt",
  "matched-line":[
    4,
    6,
    9,
    10
  ],
  "timestamp":"2022-02-03T00:03:38.195658+05:30",
  "matcher-status":true,
  "line-count":""
}
```
</details>

2022-02-10 01:05 UTC, Ice3man543 commented
The implementation has been changed to add a new `match-all` attribute to matchers which returns all matches for being used in file templates for line count calculation.

It works by default for extractors in file templates.

2022-02-10 10:21 UTC, ehsandeep approved these changes
```console
[django-framework-exceptions:exception] [file] [medium] input.txt [LN: 4,7,9,10]
```

2022-02-10 10:29 UTC, merged