Added more tests and ciphersuits for SSL protocol
projectdiscovery/nuclei pull request #1685
Opened 2022-03-07 08:38 UTC by Ice3man543

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-03-08 04:18 UTC, ehsandeep requested changes
- [ ] Exposing cipher suites and other available information as part of default response.
- [ ] Matching on `response` instead of `cipher_matched`

2022-03-08 09:25 UTC, its0x08 approved these changes

2022-03-08 15:13 UTC, ehsandeep approved these changes

2022-03-09 07:25 UTC, Mzack9999 approved these changes

2022-03-09 07:37 UTC, merged