Issue 1705 save responses on disk
projectdiscovery/nuclei pull request #1727
Opened 2022-03-17 22:02 UTC by LuitelSamikshya

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-03-31 06:40 UTC, Mzack9999 approved these changes

2022-03-31 11:22 UTC, thehackerish reviewed
I guess the README should include the new options

2022-03-31 14:01 UTC, ehsandeep requested changes
minor issue with file extension ending with `_` instead `.`
```
gslink_hackerone_com_elasticbeantalk_takeover_txt
gslink_hackerone_com_mx_fingerprint_txt
gslink_hackerone_com_mx_service_detector_txt  
```

2022-04-01 19:28 UTC, ehsandeep approved these changes

2022-04-01 19:29 UTC, merged