Extending YAML to support include and placeholders preprocessing
projectdiscovery/nuclei pull request #1767
Opened 2022-03-25 15:46 UTC by Mzack9999

## Proposed changes
This PR implements the following features:
- YAML include directive (`# !include:path/to/file.yaml`)

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-04-07 11:44 UTC, Ice3man543 approved these changes

2022-04-15 10:16 UTC, Mzack9999 commented
To improve and ease the integration with https://github.com/projectdiscovery/nuclei-burp-plugin and web-based YAML standard marshaler/unmarshaler, it would be preferred to replace the existing pattern placeholder:

```
# !include:requests.yaml
```

with the YAML marshalable:

```
import: requests.yaml
```

So that the information is not lost during conversion operations. This implies that only YAML consistent blocks would be supported (for example, it will be not feasible to include external files within a multiline string)

2022-12-13 07:34 UTC, ehsandeep requested changes
@Mzack9999 not sure if I'm doing something wrong, but I don't see any outgoing requests using shared example.

```console
$ bat requests.yaml 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: requests.yaml
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ - |
   2   │   GET /1 HTTP/1.1
   3   │   Host: {{Hostname}}
   4   │   Accept: */*
   5   │ 
   6   │ - |
   7   │   GET /2 HTTP/1.1
   8   │   Host: {{Hostname}}
   9   │   Accept: */*
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
$ bat template.yaml 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: template.yaml
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ id: CVE-2014-3206
   2   │ 
   3   │ info:
   4   │   name: test
   5   │   author: test
   6   │   severity: info
   7   │   description: test
   8   │   tags: info
   9   │ 
  10   │ requests:
  11   │   - raw:
  12   │     # !include:requests.yaml
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

$ echo https://example.com | go run . -t template.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.1

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.1 (outdated)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!
```

2022-12-13 19:35 UTC, ehsandeep approved these changes

2022-12-13 19:35 UTC, merged