[wip] Added variables for nuclei + refactor variable handling
projectdiscovery/nuclei pull request #1785
Opened 2022-03-29 20:17 UTC by Ice3man543

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-04-05 19:12 UTC, ehsandeep requested changes
merge conflict

2022-04-07 06:05 UTC, Mzack9999 approved these changes

2022-04-21 08:43 UTC, ehsandeep requested changes
We can add `variables.md` under https://github.com/projectdiscovery/nuclei-docs/tree/master/docs/templating-guide to include relevant information in docs.

2022-04-21 12:23 UTC, Ice3man543 commented
https://github.com/projectdiscovery/nuclei-docs/pull/35 - done here

2022-04-21 12:28 UTC, ehsandeep approved these changes

2022-04-21 12:29 UTC, merged