HTTP Requests Annotation Prototype
projectdiscovery/nuclei pull request #1805
Opened 2022-04-04 07:44 UTC by Mzack9999

## Proposed changes
This PR implements a proposal for http requests to override settings via annotations. Raw requests are specified as a multiline string. Protocol settings are applied at the template level for all the subsequent requests, without the possibility to override per requests setting. Here it's proposed a mechanism inspired by a few programming languages based on annotations. If specified, it allows overriding specific request settings. An annotation looks like the following snippet:

```go
@Setting:Value
```

For example, to override the real target of the request (the connection will be performed to `192.168.1.16:8000` instead of `Hostname`):

```yaml
- |
  @Host: 192.168.1.16:8000
  POST /  HTTP/1.1
  Host: {{Hostname}}

```

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-04-13 11:32 UTC, ehsandeep requested changes
@Mzack9999 we can extend this support to capture other cases, for example:

- [x] hostname input
- [x] input with scheme

currently, scheme is set based on the input target input url scheme, which will be ignored if it is defined in the template as shown below.

```yaml
- |
  @Host: 93.184.216.34
  POST /  HTTP/1.1
  Host: {{Hostname}}

- |
  @Host: example.com
  POST /  HTTP/1.1
  Host: {{Hostname}}

- |
  @Host: https://example.com
  POST /  HTTP/1.1
  Host: {{Hostname}}
```

2022-04-14 20:57 UTC, ehsandeep approved these changes

2022-04-15 12:49 UTC, Ice3man543 approved these changes

2022-04-15 13:12 UTC, ehsandeep requested changes
We can also consider adding the relevant information about this feature in the guide document for [HTTP protocol](https://github.com/projectdiscovery/nuclei-docs/blob/master/docs/templating-guide/protocols/http.md).

2022-04-16 11:53 UTC, merged