Added hang monitor for goroutine dumping
projectdiscovery/nuclei pull request #1949
Opened 2022-05-06 09:45 UTC by Ice3man543

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-05-19 12:06 UTC, Ice3man543 commented
- [ ] Add time elapsed + goroutine count monitoring

2022-05-19 15:48 UTC, Mzack9999 requested changes
Requesting changes as per https://github.com/projectdiscovery/nuclei/pull/1949#issuecomment-1131604881

2022-05-24 16:19 UTC, Mzack9999 approved these changes

2022-05-30 09:11 UTC, ehsandeep approved these changes

2022-05-30 09:11 UTC, merged