use go-homedir instead of standard os.userhomedir
projectdiscovery/nuclei pull request #2262
Opened 2022-07-07 15:03 UTC by parrasajad

## Proposed changes
`go-homedir` handles multiple edge cases of user home directory resolution.
If there is any edge case still left we can handle the error and/or introduce a flag to set a base directory for nuclei to run.

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-07-08 10:12 UTC, Mzack9999 approved these changes

2022-07-08 14:04 UTC, ehsandeep reviewed
> go-homedir handles multiple edge cases of user home directory resolution.

@parrasajad Could you please specify / detail in what manner `go-homedir` fixed the reported issue and what happened now when the user with no home directory permission runs the nuclei scan?

2022-07-09 20:46 UTC, Mzack9999 requested changes
```console
$ sudo -u nobody ./nuclei 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[ERR] Could not update templates: could not write template configuration: open /nonexistent/.config/nuclei/.templates-config.json: no such file or directory
[ERR] Could not read nuclei-ignore file: open /nonexistent/.config/nuclei/.nuclei-ignore: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10b3de0]

goroutine 1 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/catalog/loader.NewConfig(...)
	/home/user/go/src/github.com/projectdiscovery/nuclei/v2/pkg/catalog/loader/loader.go:79
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration(0xc000609ea0)
	/home/user/go/src/github.com/projectdiscovery/nuclei/v2/internal/runner/runner.go:348 +0xa40
main.main()
	/home/user/go/src/github.com/projectdiscovery/nuclei/v2/cmd/nuclei/main.go:69 +0x42f
```

2022-07-13 07:30 UTC, ehsandeep approved these changes
Can confirm the crash is fixed, other part of the issue will be fixed as part of https://github.com/projectdiscovery/nuclei/issues/1612

2022-07-13 08:01 UTC, Mzack9999 approved these changes

2022-07-13 08:03 UTC, merged

2022-07-13 10:22 UTC, jimen0 commented
Hi @Mzack9999 @parrasajad @ehsandeep - this should have updated `go.mod` too since it introduced a direct dependency.

```diff
‹dev›$ git --no-pager diff 
diff --git a/v2/go.mod b/v2/go.mod
index 5decb4ca..59a11f34 100644
--- a/v2/go.mod
+++ b/v2/go.mod
@@ -73,6 +73,7 @@ require (
 	github.com/h2non/filetype v1.1.3
 	github.com/hashicorp/go-version v1.6.0
 	github.com/mholt/archiver v3.1.1+incompatible
+	github.com/mitchellh/go-homedir v1.1.0
 	github.com/openrdap/rdap v0.9.1-0.20191017185644-af93e7ef17b7
 	github.com/projectdiscovery/iputil v0.0.0-20220620153941-036d511e4097
 	github.com/projectdiscovery/nvd v1.0.9-0.20220314070650-d4a214c1f87d
@@ -138,7 +139,6 @@ require (
 	github.com/mattn/go-runewidth v0.0.13 // indirect
 	github.com/mholt/acmez v1.0.2 // indirect
 	github.com/microcosm-cc/bluemonday v1.0.18 // indirect
-	github.com/mitchellh/go-homedir v1.1.0 // indirect
 	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
 	github.com/modern-go/reflect2 v1.0.2 // indirect
 	github.com/nwaples/rardecode v1.1.2 // indirect
```

A CI check could be easily introduced to prevent this from happening again in the future.

2022-07-13 11:09 UTC, Mzack9999 commented
Nice catch @jimen0! The check will be automated as suggested