Added ip_format dsl function + upgraded goflags
projectdiscovery/nuclei pull request #2342
Opened 2022-07-25 11:41 UTC by Ice3man543

## Proposed changes

Closes #2271

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-07-26 13:23 UTC, LuitelSamikshya approved these changes

2022-07-26 17:21 UTC, ehsandeep requested changes
<details>
<summary> 1.  crash</summary>

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{ips}}
        Origin: {{BaseURL}}

    payloads:
      ips:
        - '{{ip_format("ip", 12)}}' # no replace
```

```console
echo https://example.com | ./nuclei -t rr.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.4

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.4 (outdated)
[INF] Using Nuclei Templates 9.1.2 (latest)
[INF] Templates added in last update: 38
[INF] Templates loaded for scan: 1
panic: runtime error: index out of range [12] with length 0

goroutine 85 [running]:
github.com/projectdiscovery/mapcidr.AlterIP({0x1400013d3dc, 0x4}, {0x140009649a8?, 0x1, 0x140007ab870?}, 0x14000964bc0?, 0x0)
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.0.1/ip.go:959 +0xdfc
github.com/projectdiscovery/nuclei/v2/pkg/operators/common/dsl.init.0.func54({0x14000340be0?, 0x8?, 0x140007c1f40?})
	/Users/geekboy/Github/nuclei/v2/pkg/operators/common/dsl/dsl.go:536 +0xac
github.com/projectdiscovery/nuclei/v2/pkg/operators/common/dsl.makeDslFunction.func1.1({0x14000340be0?, 0x101bc0c80?, 0x14000964a01?})
	/Users/geekboy/Github/nuclei/v2/pkg/operators/common/dsl/dsl.go:568 +0xc4
github.com/Knetic/govaluate.makeFunctionStage.func1({0x1013e178a?, 0x101ad0ac0?}, {0x101ad0ac0, 0x14000610288?}, {0x1013da3d3?, 0x8?})
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/evaluationStage.go:243 +0x74
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x1013e178a, 0x22}, 0x1, {0x14000398fc0, 0x6, 0x8}, 0x140007c1f40, {0x1400013b578, 0x14}}, 0x140007c1f40, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:232 +0x474
github.com/Knetic/govaluate.EvaluableExpression.Eval({{0x1013e178a, 0x22}, 0x1, {0x14000398fc0, 0x6, 0x8}, 0x140007c1f40, {0x1400013b578, 0x14}}, {0x101d964d8?, ...})
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:163 +0xf0
github.com/Knetic/govaluate.EvaluableExpression.Evaluate({{0x1013e178a, 0x22}, 0x1, {0x14000398fc0, 0x6, 0x8}, 0x140007c1f40, {0x1400013b578, 0x14}}, 0xf?)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:137 +0x68
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/expressions.evaluate({0x140007d2640?, 0x140007aea20?}, 0x101380c6e?)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/expressions/expressions.go:52 +0x2a0
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/expressions.Evaluate(...)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/expressions/expressions.go:21
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).handleRawWithPayloads(0x1400096a230, {0x101d9c4e8, 0x14000826de0}, {0x140007d2640, 0x34}, {0x1400013b4e8, 0x13}, 0x1400013b488?, 0x140007ae930)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/build_request.go:245 +0xc0
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).makeHTTPRequestFromRaw(0x1400096a230?, {0x101d9c4e8?, 0x14000826de0?}, {0x1400013b4e8?, 0x13?}, {0x140007d2640?, 0x14000165348?}, 0x1007cd470?, 0x140005b8000?)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/build_request.go:234 +0xe8
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).Make(0x1400096a230, {0x101d9c4e8, 0x14000826de0}, {0x1400013b488, 0x13}, {0x140007d2640?, 0x0?}, 0x0?, 0x14000165790)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/build_request.go:102 +0x438
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0x140007d2640, 0x34}, 0x140007ae930, 0x140007ae840)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/request.go:259 +0x248
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0x140005829c0, {0x1400013b488, 0x13}, 0x140007ae840, 0x140007ae870, 0x140007ae8a0)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/http/request.go:334 +0x244
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0x140001473a0, {0x1400013b488, 0x13})
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x194
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0?, 0x0?, {0x1400013b488?, 0x0?})
	/Users/geekboy/Github/nuclei/v2/pkg/core/execute.go:142 +0xf4
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
	/Users/geekboy/Github/nuclei/v2/pkg/core/execute.go:129 +0x5a0
```

</details>

2. type `0` is currently not supported and can be retunred as array. 

<details>
<summary>3. dsl/global variable is not working</summary>

```yaml
id: basic-raw-example

info:
  name: Test RAW Template
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{ips}}
        Origin: {{BaseURL}}

    payloads:
      ips:
        - '{{ip_format(ip, 1)}}' # dsl/global variable is not working
```
</details>

2022-07-29 13:38 UTC, forgedhallpass commented
Please also extend the integration test, update and reference the documentation.

2022-11-16 08:18 UTC, Ice3man543 commented
Closed as outdated!

2022-11-16 08:18 UTC, closed without merging