Additional helpers
projectdiscovery/nuclei pull request #2359
Opened 2022-07-28 09:17 UTC by parrasajad

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-07-28 13:10 UTC, ehsandeep requested changes
We can update the dsl example to following files in [nuclei-docs](https://github.com/projectdiscovery/nuclei-docs):

docs/template-examples/helper-functions.md
docs/templating-guide/helper-functions.md

2022-07-28 13:11 UTC, ehsandeep approved these changes

2022-07-29 05:51 UTC, Mzack9999 approved these changes

2022-07-29 12:34 UTC, forgedhallpass requested changes
Please make sure to reference the work from the documentation repository, once you've finished with it.

2022-08-06 17:46 UTC, merged