Adding advanced template filtering
projectdiscovery/nuclei pull request #2374
Opened 2022-07-30 13:24 UTC by Mzack9999

## Proposed changes
This PR adds support for advanced template filtering

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-08-01 10:16 UTC, forgedhallpass requested changes
I know this is WIP, but still I'd like to mention that this will require extensive testing (multiple positive and negative scenarios) through both unit and integration tests.

2022-08-01 10:16 UTC, forgedhallpass commented on v2/pkg/catalog/loader/filter/tag_filter.go
> +		// in case of errors  => skip
At every error we should at least LOG the reason!

2022-08-22 06:12 UTC, Ice3man543 approved these changes

2022-08-22 08:20 UTC, ehsandeep requested changes
- [x] We can add the available options in the [nuclei-docs](https://github.com/projectdiscovery/nuclei-docs) for the same.
- [x] Merge conflict

2022-08-25 11:21 UTC, ehsandeep approved these changes

2022-08-25 11:22 UTC, merged