add option to specify network interface
projectdiscovery/nuclei pull request #2384
Opened 2022-08-02 13:06 UTC by parrasajad

## Proposed changes
Example:
```console
echo https://example.com | nuclei -i en0
```

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-08-03 06:06 UTC, Mzack9999 requested changes

2022-08-03 06:06 UTC, Mzack9999 commented on v2/cmd/nuclei/main.go
> +		flagSet.StringVarP(&options.Interface, "interface", "i", "", "network interface to use for network scan"),
I think the user should specify either:
- Source Ip (we need to ensure that at least one interface exists with such source IP)
- Interface and interface's Source IP (we need to ensure that the specified interface has the desired source IP)

2022-08-09 08:58 UTC, Mzack9999 requested changes
Requesting minor changes (string rename)

2022-08-09 08:58 UTC, Mzack9999 commented on v2/pkg/protocols/common/protocolstate/state.go
> +			return fmt.Errorf("sourceIP (%s) is not associated with the interface (%s)", options.SourceIP, options.Interface)
`sourceIP` => `source ip`

2022-08-09 08:58 UTC, Mzack9999 commented on v2/pkg/protocols/common/protocolstate/state.go
> +			return fmt.Errorf("sourceIP (%s) is not associated with any network interface", options.SourceIP)
`sourceIP` => `source ip`

2022-08-10 07:18 UTC, Mzack9999 approved these changes

2022-08-11 07:37 UTC, ehsandeep requested changes
- [x] Crash upon random interface input

@parrasajad 

```console
./nuclei -i ll

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.5-dev

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.5-dev (development)
[INF] Using Nuclei Templates 9.1.5 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 3835
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105227448]

goroutine 659 [running]:
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).DialTLS(0x0, {0x1061c4c50, 0x14004436d20}, {0x1057a9447, 0x3}, {0x140057c6bd0, 0x12})
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.0.16-0.20220609092737-7e3c7dcecf16/fastdialer/dialer.go:106 +0x38
net/http.(*Transport).customDialTLS(0xfe7?, {0x1061c4c50?, 0x14004436d20?}, {0x1057a9447?, 0x140066afa38?}, {0x140057c6bd0?, 0x140066afa08?})
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/net/http/transport.go:1317 +0x54
net/http.(*Transport).dialConn(0x140002b5400, {0x1061c4c50, 0x14004436d20}, {{}, 0x0, {0x14003812090, 0x5}, {0x140057c6bd0, 0x12}, 0x0})
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/net/http/transport.go:1583 +0x2bc
net/http.(*Transport).dialConnFor(0x14005f0a240?, 0x14004c7e4d0)
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/net/http/transport.go:1449 +0x80
created by net/http.(*Transport).queueForDial
	/opt/homebrew/Cellar/go/1.18.2/libexec/src/net/http/transport.go:1418 +0x39c
```

2022-08-25 12:10 UTC, ehsandeep approved these changes

2022-08-25 12:12 UTC, merged