set content_length as len(body) if response ContentLength is -1
projectdiscovery/nuclei pull request #2407
Opened 2022-08-08 10:22 UTC by parrasajad

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-08-09 08:15 UTC, Mzack9999 requested changes
Please see my comment, and let's add test cases to cover the scenarios mentioned in the issue description.

2022-08-09 08:15 UTC, Mzack9999 commented on v2/pkg/protocols/http/operators.go
> +	if resp.ContentLength > -1 {
Can we pack this into a standard helper function that calculates the correct int64 length, for example, at `github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/utils.go`?

2022-09-21 07:13 UTC, Mzack9999 requested changes
I'd recommend adding an integration test (e.g., for the `http` protocol) with a couple of requests that ensure the correct behavior for the `content_length` calculation in case the server returns the content length or the header is absent.

2022-10-24 09:53 UTC, Mzack9999 approved these changes

2022-10-24 14:36 UTC, ehsandeep approved these changes
```console
echo https://m.facebook.com | ./nuclei -t test.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.8

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.8 (latest)
[INF] Using Nuclei Templates 9.2.5 (latest)
[INF] Templates added in last update: 40
[INF] Templates loaded for scan: 1
[VER] [basic-example] Sent HTTP request to https://m.facebook.com
[2022-10-24 16:35:14] [basic-example] [http] [info] https://m.facebook.com [53888]
```

2022-10-24 14:37 UTC, merged