Added reference based tag addition to templates
projectdiscovery/nuclei pull request #2464
Opened 2022-08-21 08:59 UTC by Ice3man543

## Proposed changes

Closes #2402

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-08-21 11:32 UTC, ehsandeep approved these changes

2022-08-22 07:32 UTC, Mzack9999 requested changes
LGTM - marking as "request changes" with minor proposed changes for review

2022-08-22 07:32 UTC, Mzack9999 commented on v2/cmd/cve-annotate/main.go
> +	replaced := strings.Replace(data, tagsCurrent, fmt.Sprintf("tags: %s", strings.Join(newTags, ",")), -1)
What about `strings.ReplaceAll`?

2022-08-22 07:32 UTC, Mzack9999 commented on v2/cmd/cve-annotate/main.go
> +			if strings.HasSuffix(hostname, value) {
what do you think if we merge both conditions like:
```go
strings.HasSuffix(hostname, value) || strings.HasPrefix(reference, value)
```

2022-08-22 11:47 UTC, Mzack9999 approved these changes

2022-08-22 12:41 UTC, merged