New dsl functions
projectdiscovery/nuclei pull request #2545
Opened 2022-09-02 11:35 UTC by forgedhallpass

Closing #2544

2022-09-05 00:08 UTC, Mzack9999 requested changes
minor suggestion about optimization

2022-09-05 00:08 UTC, Mzack9999 commented on v2/pkg/operators/common/dsl/dsl.go
> +					layouts := []string{
I think we can extract these into a global package shared variable to avoid allocations at each helper call.

2022-09-06 08:37 UTC, Mzack9999 approved these changes

2022-09-06 19:14 UTC, ehsandeep approved these changes

2022-09-06 19:14 UTC, merged