Helm chart
projectdiscovery/nuclei pull request #2557
Opened 2022-09-04 17:41 UTC by heywoodlh

## Proposed changes

This adds a Helm chart so that Nuclei can be deployed easily in a Kubernetes cluster.

## Checklist

I don't think that testing is super essential with these changes, but I suppose it could be implemented with `helm template .`. If there is interest to implement this as a test I can add it.

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2022-09-04 17:42 UTC, heywoodlh commented
Documentation PR is here: https://github.com/projectdiscovery/nuclei-docs/pull/67

2022-09-04 17:58 UTC, heywoodlh commented
Some things I'd like to note:

 - Using the Helm chart as its base, I was able to write a Helm chart at my place of employment that automatically scans all our web applications in our cluster. I think Nuclei's flexibility puts it in a unique position to fill the need of network-level vulnerability scanning and fit very nicely into Kubernetes. I have found that most Kubernetes-focused vulnerability scanners only focus on the OS and package level within containers. Nuclei could very much fill that gap in a lot of Kubernetes deployments, imo.
 - The Helm chart at the moment has no method of persistence for Nuclei templates. So the Helm chart is wholly dependent upon the community templates. I'll probably update the chart with this functionality sometime this week.
 - Something like [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/) should be implemented to automatically keep the container image tags up to date in the values.yaml file

2022-09-20 09:26 UTC, ShubhamRasal requested changes

2022-09-20 09:26 UTC, ShubhamRasal commented on helm/templates/hpa.yaml
> +    name: {{ include "nuclei.fullname" . }}
can you please updae the name from `{{ include "nuclei.fullname" . }}` to `{{ include "nuclei.fullname" . }}-interactsh` ?
interactsh deployment name is wrong here

2022-10-03 10:48 UTC, ShubhamRasal approved these changes

2022-10-03 10:51 UTC, merged

2022-10-03 10:52 UTC, ehsandeep commented
@heywoodlh thank you for sharing this.