Added workflow names based condition
projectdiscovery/nuclei pull request #2594
Opened 2022-09-12 09:57 UTC by Ice3man543

## Proposed changes

Closes #2521

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-09-16 11:45 UTC, ehsandeep requested changes
We can keep using `name:` attribute instead of `names:` for multiple named matcher options to keep it uniform.

2022-09-16 17:47 UTC, ehsandeep requested changes
Workflow tests are failing

2022-09-19 06:22 UTC, parrasajad approved these changes

2022-09-19 11:19 UTC, ehsandeep approved these changes
Workflow:

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

workflows:
  - template: technologies/tech-detect.yaml
    matchers:
      - name:
          - jsdelivr
          - react
        condition: and

        subtemplates:
          - template: technologies/tech-detect.yaml
```

```console
echo https://docs.hackerone.com | ./nuclei -w test.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.8-dev

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.8-dev (development)
[INF] Using Nuclei Templates 9.1.9 (latest)
[INF] Workflows loaded for scan: 1
[tech-detect:gatsby] [http] [info] https://docs.hackerone.com
[tech-detect:jsdelivr] [http] [info] https://docs.hackerone.com
[tech-detect:react] [http] [info] https://docs.hackerone.com
```

2022-09-19 11:19 UTC, merged