Added default config generation for reporting options
projectdiscovery/nuclei pull request #2605
Opened 2022-09-15 10:30 UTC by Ice3man543

## Proposed changes

Closes #879

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-09-16 17:31 UTC, LuitelSamikshya requested changes
Test case for `customConfigDir ` needs to be modified.

2022-09-19 14:31 UTC, LuitelSamikshya approved these changes

2022-09-22 08:19 UTC, ehsandeep requested changes
Some tests are failing for the windows system.

2022-09-26 21:10 UTC, ehsandeep approved these changes
```console
ls ~/.config/nuclei

config.yaml
report-config.yaml
```

2022-09-26 21:10 UTC, merged