Added fuzzing support for query params + var dump feature
projectdiscovery/nuclei pull request #2679
Opened 2022-10-05 11:12 UTC by Ice3man543

## Proposed changes

Closes #2529 and #2670

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-10-05 14:59 UTC, ehsandeep requested changes
- [x] `payloads` to support file input
- [ ] `payloads` to support global dsl/variable
- [ ] `values` to support global dsl/variable
- [ ] `keys` to support global dsl/variable
- [ ] uniform request block
- [ ] mimic existing nuclei request behavior
- [x] lint / build fix
- [ ] docs update
- [x] keys-regex parameter add

2022-10-17 17:14 UTC, Ice3man543 commented
Docs here - https://github.com/projectdiscovery/nuclei-docs/pull/78

2022-10-30 07:38 UTC, Mzack9999 requested changes
lgtm - marking as "request changes" just to check if the following are known limitations:
* Parameters with same name are flattened (eg. `http://192.168.1.1/?id=1&id=2` => `http://192.168.1.1/?id=fuzz`)
* `replacement` seems to be literal, without the capability to refer to the existing value for some custom manipulation via DSL (eg. `{{md5(current_param_value+fuzz)}}

2022-11-01 09:09 UTC, Ice3man543 commented
@Mzack9999 made the value of the parameter accessible as DSL `value` and also fixed the multiple keys with same name issue.

```yaml
    payloads:
      reflection:
        - "1337"
   fuzzing:
      - part: query
        type: replace
        mode: single
        fuzz:
          - "{{concat(value,reflection,'somethingelse')}}"
```

```
GET /?test=new1337somethingelse HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip
```

2022-11-01 14:58 UTC, ehsandeep approved these changes

2022-11-01 14:58 UTC, merged