add dns protocol ratelimit
projectdiscovery/nuclei pull request #2763
Opened 2022-10-26 12:52 UTC by parrasajad

## Proposed changes
closes #2719 

Example:
```console
echo example.com | ./nuclei -type dns -v  -rl 1
```

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-10-27 06:50 UTC, Mzack9999 requested changes

2022-10-27 06:50 UTC, Mzack9999 commented on v2/pkg/protocols/dns/request.go
> +	request.options.RateLimiter.Take()
The rate limiter should be invoked just before sending out the request. If validation fails, we can fail early and proceed to the following item in the queue.

2022-10-28 15:30 UTC, Mzack9999 approved these changes
```console
$ time cat list.txt | go run . -id txt-fingerprint -rl 1
real    0m10.437s
$ time cat list.txt | go run . -id txt-fingerprint
real    0m5.437s
```

2022-10-29 02:29 UTC, ehsandeep approved these changes

2022-10-29 02:29 UTC, merged