Adding client/server hello in ssl templates
projectdiscovery/nuclei pull request #2782
Opened 2022-10-31 21:12 UTC by Mzack9999

## Proposed changes
This experimental PR attempts to expose client/server hello when the connection is performed with ztls. It also adds a new option `scan-mode` that defines the tlsx engine to use for tls connection.

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-11-01 08:56 UTC, Ice3man543 requested changes
@Mzack9999 it would be better if the client and server hello was exposed json marshalled since otherwise the attributes aren't very easily descriptive and matchable.

2022-11-23 13:06 UTC, Mzack9999 commented
> @Mzack9999 it would be better if the client and server hello was exposed json marshalled since otherwise the attributes aren't very easily descriptive and matchable.

do you mean as a unique string since the object is already marshaled into a sub-struct with proper json tags?

2022-11-28 08:19 UTC, Ice3man543 commented
@Mzack9999 the attributes from the `ServerHello` and `ClientHello` aren't encoded in strings in JSON and instead are displayed as integers. We should probably marshal the response separately so that they are rendered as strings.

2022-12-04 16:01 UTC, Ice3man543 approved these changes

2022-12-04 16:34 UTC, ehsandeep approved these changes

2022-12-04 16:34 UTC, merged