automerge url parameters from input and templates
projectdiscovery/nuclei pull request #3010
Opened 2022-12-09 14:38 UTC by tarunKoyalwar

## Proposed changes

- Currently when input has parameters they don't merge with template path and url parameters as discussed in  
https://github.com/projectdiscovery/nuclei/discussions/1392
- Now parameters are merged without replacing but by adding
`Ex:  https://scanme.sh/?user=pd  |  nuclei -t some-template.yaml  `
final url if `some-template.yaml` adds `user=admin` would be 
`https://scanme.sh/?user=pd&user=admin`
- This also applies for Raw requests . 

## Can be Validated Using

```sh
echo "https://scanme.sh/admin/?user=pd" | go run . -t automerge-params.yaml -silent
```

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-12-09 14:41 UTC, tarunKoyalwar commented
Example Template to validate

```yaml
id: automerge-parmas

info:
  name: Automerge templates
  author: pdtm
  severity: low
  description: Information Disclosure of Garbage Collection
  tags: exposure,devops,python

requests:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"
    matchers:
      - type: status
        status:
          - 200

  - method: POST
    path: 
      - "{{BaseURL}}?user=admin&key=val"
    matchers:
      - type: status
        status:
          - 200

  - method: GET
    path: 
      - "{{BaseURL}}/?user=admin"
    matchers:
      - type: status
        status:
          - 200
  
  - method: GET
    path: 
      - "{{BaseURL}}/django/?user=admin"
    matchers:
      - type: status
        status:
          - 200

  - raw:
      - |
        GET /?user=admin HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

    matchers:
      - type: status
        status:
          - 200

  - raw:
      - |
        GET /path/admin?user=scanme HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

    matchers:
      - type: status
        status:
          - 200

```

2022-12-09 14:42 UTC, tarunKoyalwar commented
```sh
$ echo "https://scanme.sh/admin/?user=pd" | go run . -t ~/test/automerge-params.yaml -silent  
[python-metrics] [http] [low] https://scanme.sh/admin/metrics?user=pd
[python-metrics] [http] [low] https://scanme.sh/admin/?key=val&user=pd&user=admin
[python-metrics] [http] [low] https://scanme.sh/admin/?user=pd&user=admin
[python-metrics] [http] [low] https://scanme.sh/admin/django/?user=pd&user=admin
[python-metrics] [http] [low] https://scanme.sh/admin/?user=pd&user=admin
[python-metrics] [http] [low] https://scanme.sh/admin/path/admin?user=pd&user=scanme

```

2022-12-12 12:50 UTC, tarunKoyalwar commented
# Automerge Params

- Parameters will now be automerged (base request/raw request) regardless if param is given in input or template .
- Parameters are added instead of being replaced with precedence given to input (As shown below). 

```sh
echo "https://scanme.sh/path?user=pd" | go run . -t ~/test/automerge-params.yaml  -silent
[automerge-parmas] [http] [low] https://scanme.sh/path/metrics?user=pd
[automerge-parmas] [http] [low] https://scanme.sh/path?key=val&user=pd&user=admin
[automerge-parmas] [http] [low] https://scanme.sh/path/?user=pd&user=admin
[automerge-parmas] [http] [low] https://scanme.sh/path/django/?user=pd&user=admin
[automerge-parmas] [http] [low] https://scanme.sh/path/?user=pd&user=admin
[automerge-parmas] [http] [low] https://scanme.sh/path/admin?user=pd&user=scanme
[automerge-parmas] [http] [low] https://scanme.sh/path/admin?user=pd
[automerge-parmas] [http] [low] https://scanme.sh/path?user=pd&user=scanme

```

2022-12-12 18:13 UTC, Mzack9999 requested changes
suggesting small code refactor + extra new lines

2022-12-12 18:13 UTC, Mzack9999 commented on v2/pkg/protocols/http/utils/url.go
> +		if elem2 == "" {
Unless I'm mistaken, I think this can be moved as outer if

2022-12-12 18:13 UTC, Mzack9999 commented on v2/pkg/protocols/http/utils/url.go
> +			if strings.HasSuffix(elem1, "/") && strings.HasPrefix(elem2, "/") {
This would get one level less indentation

2022-12-12 18:13 UTC, Mzack9999 commented on v2/pkg/protocols/http/utils/url_test.go
> +
extra new line

2022-12-12 18:13 UTC, Mzack9999 commented on v2/pkg/protocols/http/utils/url.go
> +
extra new line

2022-12-12 19:23 UTC, Mzack9999 approved these changes

2022-12-13 06:39 UTC, ehsandeep approved these changes

2022-12-13 06:39 UTC, merged