added check on BaseURL
projectdiscovery/nuclei pull request #3030
Opened 2022-12-12 22:38 UTC by xm1k3

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-12-13 13:11 UTC, Mzack9999 requested changes
suggesting small changes

2022-12-13 13:11 UTC, Mzack9999 commented on v2/pkg/protocols/headless/request.go
> +			if strings.Contains(actStepStr, "{{BaseURL}}") {
We can replace directly, as internally `strings.ReplaceAll` already uses `strings.Index`:
```go
actStepStr = strings.ReplaceAll(actStepStr, "{{BaseURL}}", inputURL)
```

2022-12-13 13:11 UTC, Mzack9999 commented on v2/pkg/protocols/headless/request.go
> +			reqBuilder.WriteString("\t" + actStepStr)
What about:
```go
reqBuilder.WriteString("\t" + actStepStr + "\n")
```

2022-12-14 20:57 UTC, Mzack9999 approved these changes
lgtm

2022-12-20 12:00 UTC, ehsandeep approved these changes
@xm1k3 @Mzack9999 this part can reworked in the future to make it dynamic mapping to replace with supported variables, surprisingly looks like `BaseURL` is only variable supported now in headless.

@Mzack9999 once confirmed we can create a follow-up issue to support existing global variables in headless protocol.

2022-12-20 12:00 UTC, merged

2022-12-20 15:14 UTC, xm1k3 commented
@ehsandeep yes, perhaps a good idea would be to use some sort of whitelist to manage all the keywords we need to replace
what do you think?