Issue 3046 2065 fail silently
projectdiscovery/nuclei pull request #3047
Opened 2022-12-15 17:05 UTC by xm1k3

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-12-16 13:54 UTC, Mzack9999 requested changes
- [ ] Failing tests
- [ ] Implement test cases, minimum cases to cover:
    - [ ] host inserted into the cache and multiple async calls to MarkFailed don't trigger counter reset
    - [ ] multiple calls to `cacheItem.Do()` are executed only once

2022-12-28 07:59 UTC, Mzack9999 requested changes

2022-12-28 07:59 UTC, Mzack9999 commented on v2/pkg/protocols/common/hosterrorscache/hosterrorscache_test.go
> +	for i := 0; i < 3; i++ {
This should be moved into an independent test, the test goal is to ensure that after the max error threshold the item is still there with the expected amount of errors correctly counted

2022-12-28 07:59 UTC, Mzack9999 commented on v2/pkg/protocols/common/hosterrorscache/hosterrorscache_test.go
> +func TestCacheItemCheckMarkFailedMultipleCalls(t *testing.T) {
The purpose of this test should be to call the `cache.MarkFailed` multiple times in parallell from various go routines on the same item, and like my previous comment, we need to ensure that the counter remains above the max error threshold.

2022-12-30 07:16 UTC, Mzack9999 requested changes
We also need the additional test with multiple concurrent calls to `cacheItem..Do(..)` ensuring that the function is executed only once. Something similar to this in pseudocode:
```go
var (
	count int
	item     cacheItem
)

wg := sync.waitgroup{}
for i := 0; i < xxx; i++ {
        wg.Add(1)
        go func() {
		defer wg.Done()
		item.Do(func() {
			count++
		})
	} ()
}
wg.wait()

require.Equal(t, count, 1) // ensures the increment happened only once regardless of the multiple call
```

2022-12-30 07:16 UTC, Mzack9999 commented on v2/pkg/protocols/common/hosterrorscache/hosterrorscache_test.go
> +func TestCacheMarkFailedConcurrent(t *testing.T) {
The test should look like the following one:
```go
func TestCacheMarkFailedConcurrent(t *testing.T) {
	cache := New(3, DefaultMaxHostsCount)

	tests := []struct {
		host     string
		expected int32
	}{
		{"http://example.com:80", 200},
		{"example.com:80", 200},
		{"example.com", 100},
	}

	wg := sync.WaitGroup{}
	for _, test := range tests {
		currentTest := test
		for i := 0; i < 100; i++ {
			wg.Add(1)

			go func() {
				defer wg.Done()

				cache.MarkFailed(currentTest.host, fmt.Errorf("could not resolve host"))
			}()
		}
	}

	wg.Wait()

	for _, test := range tests {
		require.True(t, cache.Check(test.host))

		normalizedCacheValue := cache.normalizeCacheValue(test.host)
		failedTarget, err := cache.failedTargets.Get(normalizedCacheValue)
		require.Nil(t, err)
		require.NotNil(t, failedTarget)

		value, ok := failedTarget.(*cacheItem)
		require.True(t, ok)
		require.EqualValues(t, test.expected, value.errors.Load())
	}
}
```
The purpose is to ensure that concurrent calls to `cache.MarkFailed` generate the final expected result (`cache.Check` true and corrent amount of errors. double for equal normalized values)

2022-12-30 10:43 UTC, xm1k3 commented on v2/pkg/protocols/common/hosterrorscache/hosterrorscache_test.go
> +func TestCacheMarkFailedMultipleCalls(t *testing.T) {
I changed the name of the test and the values of the hosts

2023-01-02 06:29 UTC, Mzack9999 approved these changes
lgtm - Asking @ehsandeep review due to go1.19 version bump

2023-01-02 08:21 UTC, ehsandeep approved these changes

2023-01-02 08:22 UTC, merged