solved problem with newExecuter
projectdiscovery/nuclei pull request #3051
Opened 2022-12-16 15:04 UTC by xm1k3

## Proposed changes

The Problem was on:

```go
...
        if options.Options.OfflineHTTP {
		template.compileOfflineHTTPRequest(options)
		return nil
	}
...
```
`template.Executer` was always nil

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-12-16 17:40 UTC, Mzack9999 requested changes
Offline matching is done only with those templates that have GET request to root URL, we should just return an error as follows:
```go
func (template *Template) compileOfflineHTTPRequest(options protocols.ExecuterOptions) error {
...
	if len(operatorsList) > 0 {
		options.Operators = operatorsList
		template.Executer = executer.NewExecuter([]protocols.Request{&offlinehttp.Request{}}, &options)
		return nil
	}
	return errors.New("template can't be used for offline matching")
}
```

2022-12-16 17:56 UTC, Mzack9999 requested changes

2022-12-16 17:56 UTC, Mzack9999 commented on v2/pkg/catalog/loader/loader.go
> +	if err == filter.ErrExcluded {
errors.Is(err, filter.ErrExcluded)

2022-12-16 17:56 UTC, Mzack9999 commented on v2/pkg/catalog/loader/loader.go
> +	if err == templates.ErrCreateTemplateExecutor {
same here

2022-12-16 17:56 UTC, Mzack9999 commented on v2/pkg/templates/compile.go
> +		err := template.compileOfflineHTTPRequest(options)
I think it's equal to just:
```go
return template.compileOfflineHTTPRequest(options)
```

2022-12-20 08:19 UTC, Mzack9999 requested changes

2022-12-20 08:19 UTC, Mzack9999 commented on v2/pkg/templates/compile.go
> +
extra new line

2022-12-20 17:50 UTC, Mzack9999 approved these changes
lgtm - error message has been made more explicit

2022-12-20 22:16 UTC, ehsandeep requested changes
@xm1k3 @Mzack9999 passive template only works with file input containing http response. Can we also do option/input validation before template parsing for input requirements?

For example -
```console
./nuclei -passive

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.2 (latest)
[INF] Templates added in last update: 57
[INF] Templates loaded for scan: 655
[INF] Targets loaded for scan: 0
[FTL] Could not run nuclei: missing required input (http response) to run passive templates
```

2022-12-28 10:23 UTC, xm1k3 commented
@ehsandeep added error message on input validation

`nuclei --passive`

```
...
...
[INF] Targets loaded for scan: 0
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: missing required input (http response) to run passive templates
```

2022-12-29 07:39 UTC, Mzack9999 commented
Due to GH inconsistent behavior - let's close this PR and create a new one

2022-12-29 07:39 UTC, closed without merging