adds scan strategy
projectdiscovery/nuclei pull request #3075
Opened 2022-12-22 10:58 UTC by tarunKoyalwar

## Proposed changes

- Adds `scan-strategy` flag to nuclei
   -  If value is `host-spray` all templates are iterated over each host
   -  If value is `template-spray` all hosts are iterated over each template
   -  If value is `auto` . [This is only a placeholder of `template-spray` for now] strategy should be selected based on given parameters and inputs.

Before this PR `template-spray` strategy was used and current default is `template-spray`

closes #3065 

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-12-22 11:13 UTC, tarunKoyalwar commented
# Flag Usage

User should select strategy based on targets . Each strategy has its own cons and pros

1.  When targets < 1000 . `template-spray` should be used . template spray type of scan is slightly faster but uses more RAM than host spray and should be used when targets < 1000 .

2. When targets > 1000 . `host-spray` should be used . host spray type of scan uses less RAM than `template-spray` and reuses connections and other small details which have major impact when targets > 1000 . 

### Note: 
the only criteria is target count . and whatever the scan strategy is selected nuclei performance will depend on below two parameters

`-bs -bulk-size : max number of hosts to scan in parallel`
`-c concurrency : max number of templates in parallel for 'given hosts' `

whatever the scan type is `-bs < -c`

2022-12-22 11:17 UTC, tarunKoyalwar commented
Integration Test fails due to `code` protocol and is not related to this PR 
```
Running test cases for "code" protocol
[✘] Test "code/test.yaml" failed: incorrect number of results: 0 (actual) vs 1 (expected) 
```

2022-12-22 17:14 UTC, Mzack9999 requested changes
lgtm - I'm proposing the following follow ups and missing TODOs:
- [x] Update docs with https://github.com/projectdiscovery/nuclei/pull/3075#issuecomment-1362714443

Create the following follow up tickets:

- [ ] Implementing `auto` strategy selection
- [ ] Tune `http.Transport` and Network settings for single-host scan (ideally no HTTP connection should be closed if RFC-compliant)

2022-12-22 20:42 UTC, tarunKoyalwar commented
- `nuclei-docs` Update PR https://github.com/projectdiscovery/nuclei-docs/pull/101
- https://github.com/projectdiscovery/nuclei/issues/3076
- https://github.com/projectdiscovery/nuclei/issues/3077

2022-12-27 20:45 UTC, ehsandeep approved these changes

2022-12-27 20:47 UTC, ehsandeep commented
@tarunKoyalwar useful addition 🎉 

@Mzack9999 merging this PR as requested changes have been updated and fail tests are the result of another known issue in GH CI - https://github.com/projectdiscovery/nuclei/issues/2969

2022-12-27 20:48 UTC, merged