fixes on passive templates
projectdiscovery/nuclei pull request #3098
Opened 2022-12-29 08:44 UTC by xm1k3

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-12-29 10:55 UTC, Mzack9999 requested changes
Todo:
- [x] When passive flag is provided we ignore all templates which are not compatible, without posting misleading errors
- [x] If no input files are provided we error out as it happens now
- [ ] We just run compatible offline templates if any on the provided files

2023-01-10 22:41 UTC, Mzack9999 requested changes

2023-01-10 22:41 UTC, Mzack9999 commented on v2/pkg/catalog/loader/loader.go
> +	if err == filter.ErrExcluded {
`errors.Is(..)`

2023-01-10 22:41 UTC, Mzack9999 commented on v2/pkg/catalog/loader/loader.go
> +	if err == templates.ErrCreateTemplateExecutor {
`errors.Is(..)`

2023-01-10 22:41 UTC, Mzack9999 commented on v2/internal/runner/runner.go
> +	if r.options.Debug {
Why are we hiding total runtime errors?

2023-01-11 12:08 UTC, Mzack9999 approved these changes

2023-01-11 12:11 UTC, Mzack9999 commented
```console
$ go run . -passive

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.6

                projectdiscovery.io

[INF] Using Nuclei Engine 2.8.6 (latest)
[INF] Using Nuclei Templates 9.3.4 (latest)
[INF] Templates added in last update: 15
[INF] Templates loaded for scan: 674
[INF] No results found. Better luck next time!
```

2023-02-06 23:40 UTC, ehsandeep approved these changes

2023-02-06 23:40 UTC, merged