Add timestamp for debug logs
projectdiscovery/nuclei pull request #3110
Opened 2023-01-01 21:55 UTC by xm1k3

## Proposed changes

Added timestamp on --debug

```
[DBG] [2023-01-01T22:48:58+01:00] ...
```

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-01-03 05:26 UTC, Mzack9999 requested changes
This approach doesn't seem very scalable. Each new added instruction will require the `.Timestamp()` call. I think we should either define an helper function that will invoke:

```go
gologger.Debug().Timestamp().Msgf("xxx)
```

or make this configurable via gologger itself, for example with global setter like:

```go
gologger.EnableTimestamp()
gologger.EnableTimestampForLevel(Debug|Info|etc)
```

2023-01-03 13:38 UTC, xm1k3 commented
Important note: 
Before merging this PR, make sure that the PR (https://github.com/projectdiscovery/gologger/issues/29) on the Logger has also been merged. The function called in this PR currently does not exist on the master branch of the Logger and would cause issues.

2023-01-04 07:57 UTC, Mzack9999 requested changes
You can test with the specific gologger commit with:
```console
go get -v github.com/projectdiscovery/gologger@1c357ca
```

2023-01-04 07:57 UTC, Mzack9999 commented on v2/cmd/nuclei/main.go
> +	logger.SetTimestamp(options.Timestamp)
```
logger.SetTimestamp(options.Timestamp, levels.LevelDebug)
```

2023-01-04 20:36 UTC, Mzack9999 requested changes
You might need to point gologger with the correct reference:
```
go get -v github.com/projectdiscovery/gologger@xxx
```

2023-01-05 15:11 UTC, Mzack9999 approved these changes

2023-01-10 12:50 UTC, ehsandeep requested changes
- [ ] failing test
- [ ] update PR with a working example.

2023-01-10 15:31 UTC, merged