fix missing trailing slash
projectdiscovery/nuclei pull request #3127
Opened 2023-01-02 16:46 UTC by tarunKoyalwar

## Proposed changes

- Fix Missing trailing slash caused by `Path.Join`

closes #3126 

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-01-02 16:46 UTC, tarunKoyalwar commented
```sh
$ go run . -u https://scanme.sh -t ~/test/raw.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4 (latest)
[INF] Using Nuclei Templates 9.3.3 (latest)
[INF] Templates added in last update: 238
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] [basic-raw-example] Dumped HTTP request for https://scanme.sh/test/..;/..;/

GET /test/..;/..;/ HTTP/1.1
Host: scanme.sh
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
Connection: close
Origin: https://scanme.sh
Accept-Encoding: gzip

[INF] No results found. Better luck next time!

```

2023-01-02 16:50 UTC, tarunKoyalwar commented
# Cause

- This was a edgecase where empty path was passed to `Path.Join` 
- Path.Join internally calls `Path.Clean` which filters out relative paths urls or other normalization 

> https://github.com/golang/go/blob/db36eca33c389871b132ffb1a84fd534a349e8d8/src/path/path.go#L51-L136

2023-01-02 17:34 UTC, ehsandeep approved these changes

2023-01-03 05:08 UTC, Mzack9999 requested changes
suggesting some minor change

2023-01-03 05:08 UTC, Mzack9999 commented on integration_tests/http/raw-path.yaml
> +  name: Test RAW Template
The `id` and `name` should mention trailing forward slash. I'd suggest something like this:
```
id: raw-with-path-final-forward-slash
name: Test Raw Request with a final forward slash in the path
```

2023-01-03 05:08 UTC, Mzack9999 commented on v2/cmd/integration-test/http.go
> +	"http/raw-path.yaml":                            &httpRawPath{},
same as before, the filename should mention the forward slash, along with the test name

2023-01-03 05:08 UTC, Mzack9999 commented on v2/cmd/integration-test/http.go
> +type httpRawPath struct{}
see my previous comment

2023-01-03 05:08 UTC, Mzack9999 commented on v2/cmd/integration-test/http.go
> +		if r.RequestURI != "/test/..;/..;/" {
Similarly to https://github.com/projectdiscovery/nuclei/blob/16d15e216c70044917d8d3180e054a019ed430d4/v2/cmd/integration-test/http.go#L468 I think we can return some expected message and match it with template matchers.

2023-01-03 18:11 UTC, Mzack9999 approved these changes

2023-01-03 18:15 UTC, merged