Markdown Reporting Index File
projectdiscovery/nuclei pull request #3129
Opened 2023-01-02 23:56 UTC by xm1k3

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-01-03 18:42 UTC, Mzack9999 requested changes

2023-01-03 18:42 UTC, Mzack9999 commented on v2/pkg/reporting/exporters/markdown/markdown.go
> +
please remove the extra new line

2023-01-03 18:42 UTC, Mzack9999 commented on v2/pkg/reporting/exporters/markdown/markdown.go
> +	file, err := os.OpenFile(filepath.Join(exporter.directory, "index.md"), os.O_CREATE|os.O_WRONLY, 0644)
Why the file index header is written over and over? Shouldn't the index creation happen in the `New(..)`?

2023-01-03 18:42 UTC, Mzack9999 commented on v2/pkg/reporting/exporters/markdown/markdown.go
> +	file, err = os.OpenFile(filepath.Join(exporter.directory, "index.md"), os.O_APPEND|os.O_WRONLY, 0644)
The variable is still referenced at line 75 (`defer file.Close()`)

2023-01-03 18:42 UTC, Mzack9999 commented on v2/pkg/reporting/exporters/markdown/markdown.go
> +	_, err = file.WriteString("|" + event.Host + "|" + event.Info.Name + "|" + event.Info.SeverityHolder.Severity.String() + "|\n")
`event.Host` as per GH issue description should be a hyperlink to the specific markdown file containing the corresponding issue detail.

2023-01-04 20:33 UTC, Mzack9999 requested changes

2023-01-04 20:33 UTC, Mzack9999 commented on v2/pkg/reporting/exporters/markdown/markdown.go
> +var indexFileName = "index.md"
`const` can be used as well

2023-01-04 20:33 UTC, Mzack9999 commented on v2/pkg/reporting/exporters/markdown/markdown.go
> +	file, err := os.OpenFile(filepath.Join(directory, indexFileName), os.O_CREATE|os.O_WRONLY, 0644)
This block can be replaced with `os.WriteFile` (as in line 99)

2023-01-05 15:52 UTC, Mzack9999 approved these changes

2023-01-15 16:30 UTC, ehsandeep approved these changes

2023-01-15 16:30 UTC, merged