fix host spray race condition
projectdiscovery/nuclei pull request #3213
Opened 2023-01-18 13:24 UTC by tarunKoyalwar

## Proposed changes

- fix race condition caused in host spray where workpool is shared for all goroutines #3140 
- removed reused code and other minor improvements
- minor code refactoring

closes #3140 

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-01-19 03:36 UTC, Ice3man543 approved these changes

2023-01-19 17:33 UTC, Mzack9999 requested changes
minor change

2023-01-20 10:22 UTC, Mzack9999 approved these changes
lgtm - nice catch on self-contained optimization!

2023-01-20 18:18 UTC, ehsandeep approved these changes

2023-01-20 18:19 UTC, merged