Use httpx as library for http probing
projectdiscovery/nuclei pull request #3261
Opened 2023-02-01 20:02 UTC by Ice3man543

## Proposed changes

Closes #3241

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-02-02 17:26 UTC, Mzack9999 requested changes
proposing http method change

2023-02-02 17:26 UTC, Mzack9999 commented on v2/internal/runner/inputs.go
> +		req, err := httpxclient.NewRequest(http.MethodGet, formedURL)
What do you think about using `HEAD` as we need to check if there is a web server (and skip body elaboration)?

2023-02-06 10:43 UTC, Mzack9999 approved these changes

2023-02-06 17:54 UTC, ehsandeep approved these changes

2023-02-06 18:04 UTC, merged