Annotate CVE: add configurations metadata
projectdiscovery/nuclei pull request #3486
Opened 2023-03-31 14:09 UTC by sduc

## Proposed changes
resolves: https://github.com/projectdiscovery/nuclei-templates/issues/6888

Update cve-annotate in order to add CVE affected configurations informations.

Currently this PR only add configurations when they are basic. The code can easily be extended to support more complex configurations using the currently empty structs (`RunningOnConfiguration` and `AdvancedConfiguration`).

Note: this PR is also pending this PR: https://github.com/projectdiscovery/nvd/pull/5 on the NVD repo. I tried running the annotate script on all the CVE templates but got blocked by NVD since I did not use an API Key. The script did work on the first couple of templates.

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-04-01 20:05 UTC, ehsandeep requested changes
@sduc this is working very well.

To avoid adding excessive information within templates.

for example:-

<details>
<summary>CVE-2022-22242</summary>

```yaml
id: CVE-2022-22242

info:
  name: Juniper Web Device Manager - Cross-Site Scripting
  author: EvergreenCartoons
  severity: medium
  description: |
    Juniper Web Device Manager (J-Web) in Junos OS contains a cross-site scripting vulnerability. This can allow an unauthenticated attacker to run malicious scripts reflected off J-Web to the victim's browser in the context of their session within J-Web, which can allow the attacker to steal cookie-based authentication credentials and launch other attacks. This issue affects all versions prior to 19.1R3-S9; 19.2 versions prior to 19.2R3-S6; 19.3 versions prior to 19.3R3-S7; 19.4 versions prior to 19.4R2-S7, 19.4R3-S8; 20.1 versions prior to 20.1R3-S5; 20.2 versions prior to 20.2R3-S5; 20.3 versions prior to 20.3R3-S5; 20.4 versions prior to 20.4R3-S4; 21.1 versions prior to 21.1R3-S4; 21.2 versions prior to 21.2R3-S1; 21.3 versions prior to 21.3R3; 21.4 versions prior to 21.4R2; 22.1 versions prior to 22.1R2.
  reference:
    - https://octagon.net/blog/2022/10/28/juniper-sslvpn-junos-rce-and-multiple-vulnerabilities/
    - https://supportportal.juniper.net/s/article/2022-10-Security-Bulletin-Junos-OS-Multiple-vulnerabilities-in-J-Web?language=en_US
    - https://kb.juniper.net/JSA69899
    - https://nvd.nist.gov/vuln/detail/CVE-2022-22242
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.1
    cve-id: CVE-2022-22242
    cwe-id: CWE-79
    configurations:
      basic:
        - cpe: cpe:2.3:o:juniper:junos:*:*:*:*:*:*:*:*
          version-end-excluding: "19.1"
        - cpe: cpe:2.3:o:juniper:junos:19.1:-:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r1-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r1-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r1-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r1-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r1-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r1-s6:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r2-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r2-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r2-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s6:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s7:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.1:r3-s8:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:-:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s6:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s7:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s8:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r1-s9:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r2-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r3-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r3-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r3-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r3-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.2:r3-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:-:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r1-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r2-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r2-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r2-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r2-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r2-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r2-s6:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r3-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r3-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r3-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r3-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r3-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.3:r3-s6:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:-:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r1-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r1-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r1-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r1-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r2-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r2-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r2-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r2-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r2-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r2-s6:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s5:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s6:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s7:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:19.4:r3-s8:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:-:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r1-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r1-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r1-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r1-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r2-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r2-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r3-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r3-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r3-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.1:r3-s4:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:-:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r1-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r1-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r1-s3:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r2-s1:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r2-s2:*:*:*:*:*:*
        - cpe: cpe:2.3:o:juniper:junos:20.2:r2-s3:*:*:*:*:*:*
        - c [...]

2023-04-05 06:25 UTC, ehsandeep commented
> You are suggesting regardless of how many versions/entries we have in the configurations we just include the CPE without the version number and the EPSS Score (even when the config has just one entry like in my example with `CVE-2022-46888`)?

Right, for the time being, we can exclude the version information to write within the template and only add `cpe` info at the root of the `classification` section. @sduc

2023-04-12 07:34 UTC, sduc commented
Sorry for the long wait @ehsandeep . Had some other priorities. I made the changes according to your last comment. Let me know.

2023-04-12 10:49 UTC, ehsandeep approved these changes

2023-04-12 10:49 UTC, merged