Extending multistep support
projectdiscovery/nuclei pull request #3546
Opened 2023-04-14 17:36 UTC by Mzack9999

## Proposed changes
WIP

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-04-16 17:13 UTC, ehsandeep requested changes
```console
[WRN] Could not make network request for XXXXX:9100: could not write request to server: write tcp 192.168.1.232:65427->XXXXX:9100: write: broken pipe
panic: runtime error: slice bounds out of range [:13] with length 0

goroutine 99 [running]:
github.com/projectdiscovery/dsl.init.0.func70({0xc000720100, 0x3, 0x16?})
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/dsl@v0.0.6-0.20230415194237-c0a24b744cfb/dsl.go:791 +0x1d4
github.com/projectdiscovery/dsl.dslFunction.Exec({{0x101a11462, 0x6}, 0x0, {0xc0002497c0, 0x1, 0x1}, 0x101f17350}, {0xc000720100, 0x3, 0x4})
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/dsl@v0.0.6-0.20230415194237-c0a24b744cfb/func.go:52 +0x143
github.com/Knetic/govaluate.makeFunctionStage.func1({0xc00056ecd0?, 0x101642080?}, {0x101642080, 0xc000265470?}, {0x101ab3dd0?, 0xc00056ef01?})
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/evaluationStage.go:243 +0x67
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056ed20, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:232 +0x5dc
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056ed70, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056edc0, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056ee10, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056ee60, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056eeb0, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056ef00, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056ef50, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056efa0, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc00056eff0, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.Eval({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, {0x10229db60, ...})
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:163 +0x125
github.com/Knetic/govaluate.EvaluableExpression.Evaluate({{0x101abcdc8, 0x22}, 0x1, {0xc000b8cf00, 0x17, 0x20}, 0xc00056eff0, {0xc0004584e2, 0x4e}}, 0xc000a79fb0)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:137 +0x9c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/expressions.evaluate({0xc000458480?, 0xc000458420?}, 0x52?)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/expressions/expressions.go:52 +0x198
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/expressions.EvaluateByte(...)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/expressions/expressions.go:31
github.com/projectdiscovery/nuclei/v2/pkg/protocols/network.(*Request).executeRequestWithPayloads(0xc000be3000, 0xc0007af808, {0xc000730060, 0x14}, {0xc000730018, 0x14}, {0xc000730018, 0x14}, 0x0, 0xc0009aeae0, ...)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/network/request.go:148 +0x646
github.com/projectdiscovery/nuclei/v2/pkg/protocols/network.(*Request).executeAddress(0xc000be3000, 0xc0007a5c10, {0xc000730060, 0x14}, {0xc000730018, 0x14}, {0xc000730018, 0x14}, 0x0?, 0xc0009ae2a0, ...)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/network/request.go:96 +0x666
github.com/projectdiscovery/nuclei/v2/pkg/protocols/network.(*Request).ExecuteWithResults(0xc000be3000, 0xc0007ec060, 0x103155df8?, 0x100025cc7?, 0x101010001?)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/network/request.go:61 +0x392
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc00052c060, 0xc0007ec000)
	/Users/geekboy/Github/nuclei/v2/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x365746?, 0x1?, 0xc000acaba0)
	/Users/geekboy/Github/nuclei/v2/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
	/Users/geekboy/Github/nuclei/v2/pkg/core/executors.go:105 +0x4f8
panic: runtime error: slice bounds out of range [:13] with length 0

goroutine 95 [running]:
github.com/projectdiscovery/dsl.init.0.func70({0xc000796100, 0x3, 0x16?})
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/dsl@v0.0.6-0.20230415194237-c0a24b744cfb/dsl.go:791 +0x1d4
github.com/projectdiscovery/dsl.dslFunction.Exec({{0x101a11462, 0x6}, 0x0, {0xc0002497c0, 0x1, 0x1}, 0x101f17350}, {0xc000796100, 0x3, 0x4})
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/dsl@v0.0.6-0.20230415194237-c0a24b744cfb/func.go:52 +0x143
github.com/Knetic/govaluate.makeFunctionStage.func1({0xc00079be50?, 0x101642080?}, {0x101642080, 0xc0007f2198?}, {0x101ab3dd0?, 0xc000a04101?})
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/evaluationStage.go:243 +0x67
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000996600, 0x17, 0x20}, 0xc000a041e0, {0xc0007f84e2, 0x4e}}, 0xc00079bef0, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:232 +0x5dc
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000996600, 0x17, 0x20}, 0xc000a041e0, {0xc0007f84e2, 0x4e}}, 0xc00079bf40, ...)
	/Users/geekboy/go/pkg/mod/github.com/!knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible/EvaluableExpression.go:205 +0x3b5
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x101abcdc8, 0x22}, 0x1, {0xc000 [...]

2023-04-16 18:17 UTC, Mzack9999 commented
- [ ] Incorrect checks on byte stream slice bounds

2023-04-25 17:34 UTC, Mzack9999 commented
- [ ] Add loop/placeholder support
- [ ] Test with mssql fingerprinting/bruteforcing (ref: https://github.com/projectdiscovery/nuclei/discussions/3374)

2023-04-27 21:55 UTC, tarunKoyalwar reviewed
implementation lgtm !

@Mzack9999   cannot reproduce couchdb rce locally , 
```console
$ ./nuclei -u 127.0.0.1 -v -t ~/test-templates/couchdb.yaml -debug   -svd                     

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

		projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (development)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[DBG] Protocol request variables: 
	1. challenge_reply => 00157201020304
	2. cookie => monster
	3. cmd => 0000006670836804610667770 .... 16b000269646a770475736572
	4. Host => 127.0.0.1
	5. Hostname => 127.0.0.1
	6. name_msg => 00156e00070003499c4141414141414041414141414141

[WRN] [CVE-2022-24706] Could not make network request for (127.0.0.1:9100) : [:RUNTIME] could not read response from connection <- EOF
[INF] No results found. Better luck next time!

```

2023-04-27 21:56 UTC, tarunKoyalwar commented
![Screenshot 2023-04-28 at 3 25 56 AM](https://user-images.githubusercontent.com/45962551/234999669-8a55d753-4e5d-47e9-8575-cb290b06d88f.png)

2023-06-01 00:49 UTC, ehsandeep approved these changes

2023-06-01 00:49 UTC, merged