Add utility to write max-requests to templates
projectdiscovery/nuclei pull request #3607
Opened 2023-04-25 07:12 UTC by RamanaReddy0M

## Proposed changes
- #3443 Utility to calculate / write max request counter for nuclei templates 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-04-25 10:29 UTC, ehsandeep requested changes
- [x] Failed to add a counter for templates with no `metadata` attribute, we can add a counter along with metadata attribute if not available in the template.
- [ ] Remove redundant option `-d` and update `-i` flag to accept template file or directories with templates.
- [ ] Adding verbose mode `-v` to include display/errors?

2023-04-26 18:41 UTC, ehsandeep approved these changes

2023-05-01 07:56 UTC, ehsandeep requested changes
CVE annotation functionality is not working with new changes.

2023-05-02 18:09 UTC, ShubhamRasal commented
- [ ] max-requests not working with race condition templates

2023-05-09 10:46 UTC, ShubhamRasal approved these changes

2023-05-09 17:59 UTC, ehsandeep approved these changes

2023-05-09 17:59 UTC, merged