support for dynamic variables in template context
projectdiscovery/nuclei pull request #3672
Opened 2023-05-11 13:53 UTC by tarunKoyalwar

## Proposed changes

- adds support for dynamic variables in template context (i.e when template contains more than 1 protocol)
- adds support for multi protocol request execution
- closes #3413 

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-05-13 16:51 UTC, ehsandeep requested changes
we can also expose protocol level global variables (prefixed by protocol name) in template context to use with other protocols.

example added in https://github.com/projectdiscovery/nuclei/issues/3413

2023-05-24 14:52 UTC, Mzack9999 commented
Recommendations:
- Consider passing to next steps only named extractors with a unique value as a start, this resolves the issue to prefix the name with the protocol. This drops the need to prefix the protocol to the name.
- Evaluate if the contextargs mechanism might be a suitable transport vector for bringing in/out values from protocol context
- interactsh handling might not be possible (ref. https://github.com/projectdiscovery/nuclei/issues/3437 and https://github.com/projectdiscovery/nuclei/pull/2930#issuecomment-1558575851)

2023-05-24 21:45 UTC, tarunKoyalwar commented
### New Changes
- use `contextArgs` to pass and add values to map in template context
- fix race condition in contextArgs
- add design related docs related to multi protocol at https://github.com/projectdiscovery/nuclei/tree/issue-3413-multi-proto-support/v2/pkg/protocols/multi#readme
- sort keys before vardump
- unless template is a multi protocol all logic is no-op (this reduces memory consumption of maps compared to earlier implementation)

### To Discuss / Confirm ?
- in mulit protocol template all protocol response fields are prefixed with protocol ex: `http_status_code` . just in case `status_code` variables is also available in matchers/extractors should that be removed ?? (cc: @ehsandeep , @Mzack9999 )

2023-05-24 21:46 UTC, tarunKoyalwar commented
### example complex template

```yaml
id: nuclei-multi-protocol

info:
  name: multi protocol support
  author: pdteam
  severity: info

variables:
  # we can use variables as pre-processing since it is evaluated after each protocol
  # example replace CN= prefix from ssl_subject_dn
  subject_dn_filtered: '{{replace(ssl_subject_dn,"CN=","")}}' # ssl_subject_dn is obtained from ssl
  # subject_dn_filtered is used in http protocol

dns:
  - name: "{{FQDN}}" # dns request 
    type: cname

ssl:
  - address: "{{Hostname}}" # ssl request

http:
  - method: GET
    path:
      - "{{BaseURL}}" # http request

    headers:
      Host: "{{ssl_subject_cn}}" # host extracted from ssl request
      Cipher: "{{ssl_cipher}}"

    matchers:
      - type: dsl
        dsl:
          # - contains(http_body,'File not found') # check for http string
          - http_status_code == 404
          - contains(dns_cname, 'github.io') # check for cname
          - subject_dn_filtered == 'mta-sts.managed.hackerone.com'
        condition: and 
```

```console
$ ./nuclei -u mta-sts.managed.hackerone.com -t ~/test-templates/multiprotocomplex.yaml  -ms

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.5-dev

		projectdiscovery.io

[WRN] Found 24 templates loaded with deprecated paths, update before v2.9.5 for continued support.
[INF] Current nuclei version: v2.9.5-dev (development)
[INF] Current nuclei-templates version: v9.5.0 (latest)
[INF] New templates added in latest release: 62
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[nuclei-multi-protocol] [matched] [http] [info] https://mta-sts.managed.hackerone.com
```

2023-05-24 21:52 UTC, tarunKoyalwar commented
- requested review regarding implmentation before proceeding with tests & docs

2023-05-25 09:53 UTC, Mzack9999 requested changes
Neat implementation with full reuse of `contextargs` transport vector as it was designed - I'm suggesting some minor changes and a potential new helper for utils.

Note: the smart-input functionality only executes multiprotocol templates if the first in-order protocol matches the input type and blocks at any intermediate step when the input doesn't match the protocol type.

2023-05-29 15:02 UTC, tarunKoyalwar commented on v2/pkg/protocols/common/utils/vardump/dump.go
> +	keys := maps.Keys(data)
done

2023-05-30 06:07 UTC, Mzack9999 approved these changes
lgtm! - Just suggesting to consider using synclock map from the maputils package as it's safe for concurrent access and with protected versions of various methods

2023-06-05 21:04 UTC, tarunKoyalwar commented
@ehsandeep  @ShubhamRasal  will add docs related to multi protocol in nuclei-docs soon . requesting final review regarding  this PR

2023-06-06 10:03 UTC, ShubhamRasal approved these changes
lgtm 🚀 🔥

2023-06-06 16:20 UTC, tarunKoyalwar commented
### Documentation

- [ ] https://github.com/projectdiscovery/nuclei-docs/pull/151

2023-06-09 00:17 UTC, ehsandeep approved these changes
@tarunKoyalwar merge conflict ^

2023-06-09 14:22 UTC, merged