Issue 2693 bug in matcher status
projectdiscovery/nuclei pull request #3770
Opened 2023-06-01 02:07 UTC by RamanaReddy0M

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-06-05 20:05 UTC, tarunKoyalwar requested changes
requesting minor changes + add new flag to control behaviour of matcher status at template scope vs per request

2023-06-05 20:05 UTC, tarunKoyalwar commented on v2/pkg/protocols/common/executer/executer.go
>  // Executer executes a group of requests for a protocol
@RamanaReddy0M requesting minor change regarding implementation . we can move this variable to types.Options and access it here in Executor with `e.options.Options.MatchStatusPerRequest`

also this variable seems to  be unused and hence always false

- [ ] add new flag `-msr -matcher-status-request` to show matcher status per request (use ^ variable)

2023-06-13 14:13 UTC, tarunKoyalwar requested changes
`-msr` should implicitly enable `-ms` to avoid conflicting scenarios
```
$ ./nuclei -u example.com -id CVE-2021-29490  -msr   

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

		projectdiscovery.io

[WRN] Found 3 templates loaded with deprecated protocol syntax, update before v2.9.5 for continued support.
[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.2 (latest)
[INF] New templates added in latest release: 50
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[CVE-2021-29490] [http] [medium] https://example.com
[CVE-2021-29490] [http] [medium] https://example.com
[INF] No results found. Better luck next time!
```

^ output shows that target is vulnerable but actually i.e matcher status (and status is omitted)

- suggesting updating PR description with POC . ex: command to run to test implementation

2023-06-13 14:13 UTC, tarunKoyalwar commented on v2/cmd/integration-test/http.go
>  }
add new integration test along with this one where we use `-msr` flag

2023-06-13 14:13 UTC, tarunKoyalwar commented on v2/pkg/output/output.go
>  		return nil
@RamanaReddy0M  is it possible to handle all logic related to matchers status per request in common/executer/executer.go . without updating  writer methods ??

2023-06-21 13:46 UTC, RamanaReddy0M commented
- matcher-status
```console
✗ ./nuclei -u example.com -id CVE-2021-29490  -ms 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[CVE-2021-29490] [failed] [http] [medium] https://example.com
```

- matcher status per request
```console
✗ ./nuclei -u example.com -id CVE-2021-29490  -msr

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

                projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] New templates added in latest release: 82
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[CVE-2021-29490] [failed] [http] [medium] https://example.com
[CVE-2021-29490] [failed] [http] [medium] https://example.com
```

2023-06-26 13:49 UTC, tarunKoyalwar approved these changes
lgtm !

## when using `-msr` (matcher status per request)
```console
$ echo https://example.com | ./nuclei -tags oast -msr -silent | sort | uniq -c | sort -r
   7 [CVE-2023-27350] [failed] [http] [critical] https://example.com
   5 [request-based-interaction] [failed] [http] [info] https://example.com
   4 [CVE-2022-22965] [failed] [http] [critical] https://example.com
   3 [umbraco-base-ssrf] [failed] [http] [medium] https://example.com
   3 [fastjson-1-2-68-rce] [failed] [http] [critical] https://example.com
   3 [CVE-2022-22947] [failed] [http] [critical] https://example.com
   3 [CVE-2022-21587] [failed] [http] [critical] https://example.com
   3 [CVE-2020-28976] [failed] [http] [medium] https://example.com
   2 [fastjson-1-2-24-rce] [failed] [http] [critical] https://example.com
   2 [apache-solr-log4j-rce] [failed] [http] [critical] https://example.com
   2 [CVE-2022-31814] [failed] [http] [critical] https://example.com
   2 [CVE-2022-26134] [failed] [http] [critical] https://example.com
   2 [CVE-2022-24112] [failed] [http] [critical] https://example.com
   2 [CVE-2022-22972] [failed] [http] [critical] https://example.com
   2 [CVE-2021-44228] [failed] [http] [critical] https://example.com
   2 [CVE-2021-29490] [failed] [http] [medium] https://example.com
   2 [CVE-2021-21881] [failed] [http] [critical] https://example.com
   2 [CVE-2021-1497] [failed] [http] [critical] https://example.com
   2 [CVE-2020-28188] [failed] [http] [critical] https://example.com
   2 [CVE-2020-25506] [failed] [http] [critical] https://example.com
   2 [CVE-2020-17456] [failed] [http] [critical] https://example.com
   2 [CVE-2019-20224] [failed] [http] [high] https://example.com
   2 [CVE-2019-12988] [failed] [http] [critical] https://example.com
   2 [CVE-2019-12987] [failed] [http] [critical] https://example.com
   2 [CVE-2019-12986] [failed] [http] [critical] https://example.com
   2 [CVE-2019-12985] [failed] [http] [critical] https://example.com
   2 [CVE-2018-10818] [failed] [http] [critical] https://example.com
   2 [CVE-2018-10562] [failed] [http] [critical] https://example.com
   2 [CVE-2017-10271] [failed] [http] [high] https://example.com
   1 [zimbra-preauth-ssrf] [failed] [http] [critical] https://example.com
   1 [xenmobile-server-log4j] [failed] [http] [critical] https://example.com
   1 [wp-xmlrpc-pingback-detection] [failed] [http] [info] https://example.com
   1 [wordpress-ssrf-oembed] [failed] [http] [medium] https://example.com
```

## when using `-ms` match (matcher status)
```console
$  echo https://example.com | ./nuclei -tags oast -ms -silent | sort | uniq -c | sort -r
   1 [zimbra-preauth-ssrf] [failed] [http] [critical] https://example.com
   1 [xenmobile-server-log4j] [failed] [http] [critical] https://example.com
   1 [wp-xmlrpc-pingback-detection] [failed] [http] [info] https://example.com
   1 [wordpress-ssrf-oembed] [failed] [http] [medium] https://example.com
   1 [webpagetest-ssrf] [failed] [http] [high] https://example.com
   1 [vrealize-operations-log4j-rce] [failed] [http] [critical] https://example.com
   1 [vmware-vcenter-ssrf] [failed] [http] [critical] https://example.com
   1 [vmware-vcenter-log4j-jndi-rce] [failed] [http] [critical] https://example.com
   1 [vmware-siterecovery-log4j-rce] [failed] [http] [critical] https://example.com
   1 [vmware-operation-manager-log4j] [failed] [http] [critical] https://example.com
   1 [vmware-nsx-log4j] [failed] [http] [critical] https://example.com
   1 [vmware-horizon-log4j-jndi-rce] [failed] [http] [critical] https://example.com
   1 [vmware-hcx-log4j] [failed] [http] [critical] https://example.com
   1 [unifi-network-log4j-rce] [failed] [http] [critical] https://example.com
   1 [unauth-ztp-ping] [failed] [http] [high] https://example.com
   1 [umbraco-base-ssrf] [failed] [http] [medium] https://example.com
   1 [tls-sni-proxy] [failed] [http] [info] https://example.com
   1 [targa-camera-ssrf] [failed] [http] [high] https://example.com
   1 [ssrf-via-oauth-misconfig] [failed] [http] [medium] https://example.com
   1 [springboot-log4j-rce] [failed] [http] [critical] https://example.com
```

### Note:
`-msr` does not show matchers status of each matcher ❌ 
it shows matcher status if there are multiple requests 👍

2023-06-26 19:20 UTC, ehsandeep requested changes
```console
./nuclei -pt tcp -tags cve -ms -u 1.1.1.1
```

- [x] not working with network protocol

2023-06-27 18:18 UTC, RamanaReddy0M commented
```console
✗ ./nuclei -pt tcp -tags cve -ms -u 1.1.1.1 -silent
[CVE-2022-31793] [failed] [tcp] [high] 1.1.1.1
[CVE-2018-2628] [failed] [tcp] [critical] 1.1.1.1
[CVE-2016-2004] [failed] [tcp] [critical] 1.1.1.1
[CVE-2022-24706] [failed] [tcp] [critical] 1.1.1.1
[CVE-2015-3306] [failed] [tcp] [high] 1.1.1.1
[CVE-2017-3881] [failed] [tcp] [critical] 1.1.1.1
[CVE-2023-33246] [failed] [tcp] [critical] 1.1.1.1
[CVE-2020-1938] [failed] [tcp] [critical] 1.1.1.1
[CVE-2016-3510] [failed] [tcp] [critical] 1.1.1.1
[CVE-2021-44521] [failed] [tcp] [critical] 1.1.1.1
[CVE-2001-1473] [failed] [tcp] [high] 1.1.1.1
[CVE-2020-7247] [failed] [tcp] [critical] 1.1.1.1
[CVE-2018-2893] [failed] [tcp] [critical] 1.1.1.1
[CVE-2022-0543] [failed] [tcp] [critical] 1.1.1.1
[CVE-2011-2523] [failed] [tcp] [critical] 1.1.1.1
```

2023-06-30 13:26 UTC, ehsandeep requested changes
`-ms` option working as expected, we can remove `-msr` option as this feature is focused on template level match / fail status only.

-  [x] remove `-msr` option

Note: for later, `-ms` option does not consider the template failed to execute because of missing dynamic variable as failed.

2023-06-30 18:01 UTC, ehsandeep approved these changes

2023-06-30 18:02 UTC, merged