Use templateman enhance api to populate CVE info
projectdiscovery/nuclei pull request #3788
Opened 2023-06-06 07:12 UTC by RamanaReddy0M

## Proposed changes

2023-06-08 04:12 UTC, RamanaReddy0M commented
depends on: https://github.com/projectdiscovery/templateman/pull/81

2023-06-16 17:28 UTC, ehsandeep requested changes
- [x] print `max-request` update only when updated
- [ ] print `format` update only when updated
- [ ] template unmarshal error


```console
[max-request] ❌ template: /Users/geekboy/Github/nuclei/v2/cmd/tmc/test.yaml err: yaml: unmarshal errors:
  line 7: cannot unmarshal !!str `- https...` into []string
  ```
  
  Template used for testing:
  
  ```yaml
  id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  reference: |
    - https://test.com

http:
  - method: GET
    path:
      - "{{BaseURL}}"
```

2023-06-19 21:51 UTC, ehsandeep requested changes
`self-contained: true` is getting removed with `-mr` option. @RamanaReddy0M 

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

self-contained: true
http:
  - method: GET
    path:
      - "https://example.com"
```

```
./tmc -i test.yaml -mr
```

2023-06-21 13:19 UTC, ehsandeep approved these changes
```console
./tmc -i test.yaml -mr -f -v -l -e

[max-request] ✅ updated template: /Users/geekboy/Github/nuclei/v2/cmd/tmc/test.yaml
[format] ✅ formated template: /Users/geekboy/Github/nuclei/v2/cmd/tmc/test.yaml
[lint] ✅ lint template: /Users/geekboy/Github/nuclei/v2/cmd/tmc/test.yaml
[validate] ✅ validated template: /Users/geekboy/Github/nuclei/v2/cmd/tmc/test.yaml
[enhance] ✅ updated template: /Users/geekboy/Github/nuclei/v2/cmd/tmc/test.yaml
```

2023-06-21 13:19 UTC, merged