add headless options flag
projectdiscovery/nuclei pull request #3951
Opened 2023-07-19 09:18 UTC by dogancanbakir

## Proposed changes

Adds a flag for additional chrome options that can be specified using -headless-options, for example:
```
nuclei -u https://tesla.com -headless  -headless-options --no-sandbox,proxy-server=http://127.0.0.1:8080
```

## Checklist

- [X] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-07-22 09:09 UTC, ehsandeep approved these changes
feature is working as expected, not sure if we can make use of env variable to disable specific test based on OS instead of code change? cc @Mzack9999

2023-07-24 11:53 UTC, Mzack9999 requested changes

2023-07-24 11:53 UTC, Mzack9999 commented on v2/cmd/integration-test/integration-test.go
> +	DisableOn []string
What about turning `DisableOn` into a callback like `func() bool` so that additional logic can be implemented if necessary

2023-07-24 11:53 UTC, Mzack9999 commented on v2/cmd/integration-test/interactsh.go
> +	{DisableOn: []string{"windows", "darwin"}, Path: "http/interactsh.yaml", TestCase: &httpInteractshRequest{}},
As per the previous comment I would change this to:
```go
func() bool { return osutil.IsWindows() || osutil.IsDarwin() }
```
and move it as last item of the list for readability

2023-07-24 11:53 UTC, Mzack9999 commented on v2/cmd/integration-test/loader.go
> +	{DisableOn: nil, Path: "loader/template-list.yaml", TestCase: &remoteTemplateList{}},
We can omit `DisableOn: nil` since `nil` is the default value

2023-07-27 09:15 UTC, Mzack9999 approved these changes
lgtm - Test failure tracked at https://github.com/projectdiscovery/nuclei/issues/3987 (excluding temporary)

2023-07-28 15:50 UTC, merged