ignore version parsing error
projectdiscovery/nuclei pull request #3984
Opened 2023-07-26 12:57 UTC by tarunKoyalwar

2023-07-26 13:03 UTC, tarunKoyalwar commented
### `SHOW_DSL_ERRORS` env
- since errors may be required in some cases . setting this env variable will show ignored dsl errors
```console
$ SHOW_DSL_ERRORS=true ./nuclei -u https://example.com -t ~/test-templates/comparewarning.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.9

		projectdiscovery.io

[INF] Current nuclei version: v2.9.9 (latest)
[INF] Current nuclei-templates version: v9.5.8 (latest)
[INF] New templates added in latest release: 113
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[VER] [basic-example] Sent HTTP request to https://example.com
[WRN] [basic-example] error parsing argument value
[INF] No results found. Better luck next time!
```

2023-07-26 21:38 UTC, ehsandeep approved these changes

2023-07-27 09:31 UTC, Mzack9999 requested changes
Implementation: lgtm!
I'd recommend to also add:
- [x] Integration Tests
- [ ] Update docs if necessary with new ENV variable flag explanation (I'm not sure if we have already a section for this)

2023-07-28 13:36 UTC, tarunKoyalwar commented
depends on https://github.com/projectdiscovery/dsl/pull/68

2023-07-28 13:38 UTC, tarunKoyalwar commented
@Mzack9999 @ehsandeep  , created new file `DEBUG.md` to track all debugging options available in nuclei https://github.com/projectdiscovery/nuclei/blob/issue-3950-dsl-warning/DEBUG.md

i think it will also be helpful for other teams

2023-07-28 15:34 UTC, merged