remove duplicated outputwriter(interactsh) call
projectdiscovery/nuclei pull request #4042
Opened 2023-08-11 14:30 UTC by tarunKoyalwar

2023-08-12 08:17 UTC, ehsandeep approved these changes

2023-08-14 07:57 UTC, dogancanbakir approved these changes
LGTM

```console
$ go run . -t http/cves/2023/CVE-2023-26067.yaml -u http://target

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.11-dev

                projectdiscovery.io

[INF] Current nuclei version: v2.9.11-dev (development)
[INF] Current nuclei-templates version: v9.6.1 (latest)
[INF] New templates added in latest release: 198
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.live
[CVE-2023-26067] [http] [high] http://target/cgi-bin/fax_change_faxtrace_settings
```

2023-08-14 08:37 UTC, Mzack9999 requested changes
When there is only one interactsh matcher it doesn't seem to work:
```console
$ cat test.yaml
id: test

info:
  name: test
  author: test
  severity: info
  description: test
  tags: cve

http:
  - raw:
      - |
        POST / HTTP/1.1
        Host: {{Hostname}}
        
        {{interactsh-url}}

    matchers:
      - type: dsl
        dsl:
          - contains(interactsh_protocol, 'http')
$ go run . -u https://scanme.sh -t test.yaml -v -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.11-dev

                projectdiscovery.io

[INF] Current nuclei version: v2.9.11-dev (development)
[INF] Current nuclei-templates version: v9.6.1 (latest)
[INF] New templates added in latest release: 198
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.site
[INF] [CVE-2023-26067] Dumped HTTP request for https://scanme.sh/

POST / HTTP/1.1
Host: scanme.sh
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
Connection: close
Content-Length: 43
Accept-Encoding: gzip

cjcud9h3gitpq7sf2qm0isfmffn9qiusz.oast.site
[DBG] [CVE-2023-26067] Dumped HTTP response https://scanme.sh/

HTTP/1.1 200 OK
Connection: close
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Mon, 14 Aug 2023 08:32:40 GMT

ok
[cjcud9h3gitpq7sf2qm0isfmffn9qiusz] Received HTTP interaction from xx.xx.xx.xx at 2023-08-14 08:32:42
------------
HTTP Request
------------

GET / HTTP/1.1
Host: cjcud9h3gitpq7sf2qm0isfmffn9qiusz.oast.site
Accept-Encoding: gzip
Connection: close
User-Agent: Go-http-client/1.1




------------
HTTP Response
------------

HTTP/1.1 200 OK
Connection: close
Content-Type: text/html; charset=utf-8
Server: oast.site
X-Interactsh-Version: 1.1.5

<html><head></head><body>zsuiq9nffmfsi0mq2fs7qptig3h9ducjc</body></html>
```
The file [`github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go`](https://github.com/projectdiscovery/nuclei/blob/04953ebe96361c21670cfb502ee891b70f3af709/v2/pkg/protocols/http/request.go#L572) was patched to simulate requests to the generated urls with the following snippet:
```go
for _, u := range generatedRequest.interactshURLs {
	httpclient.Get(u)
}
```

2023-08-16 12:49 UTC, tarunKoyalwar commented
@Mzack9999 . closing this PR as implementation needs to be revisited completely -> more info at https://github.com/projectdiscovery/nuclei/issues/4041#issuecomment-1680542127

will create new PR with new implementation

2023-08-16 12:49 UTC, closed without merging