Gitlab tracker: Duplicate issues
projectdiscovery/nuclei pull request #4152
Opened 2023-09-15 08:07 UTC by skahn007gl

## Proposed changes

Small update to Gitlab tracker to remove duplicate issue creation for duplicate findings.
Instead of raising a new issue, the newest existing issue updated with a comment containing the new findings and re-opened if required.

## Checklist

- [X] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [X] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2023-09-18 10:25 UTC, dogancanbakir requested changes
LGTM -left a comment for doc update.

2023-09-18 10:33 UTC, dogancanbakir commented
Forgot to add `duplicate-issue-check: true` in config. Checking it again.. 🤦

2023-09-18 10:38 UTC, dogancanbakir commented on docs/getting-started/running.mdx
>  | **Platform** | GitHub
Could you please include the `duplicate-issue-check: true` in the "Nuclei Reporting" section as well?

2023-09-20 04:03 UTC, dogancanbakir approved these changes
LGTM

2023-09-25 17:25 UTC, ehsandeep approved these changes

2023-09-25 17:25 UTC, merged