WIP: add 'fs' module to javascript protocol
projectdiscovery/nuclei pull request #4156
Opened 2023-09-15 21:59 UTC by tarunKoyalwar

## Proposed changes

- add 'fs' module to list directory and read files (all while respecting sandbox)
- add 'init' block to execute javascript code to initialize template
- add 'updatePayload' and 'set' to set values to 'payloads' and 'args' respectively

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-09-21 12:09 UTC, Mzack9999 requested changes
Implementation: lgtm
notes: minor debug code leftover

2023-09-21 12:09 UTC, Mzack9999 commented on v2/pkg/protocols/javascript/js.go
> +						fmt.Print("got match\n")
i guess this is forgotten debug code

2023-09-21 12:09 UTC, Mzack9999 commented on v2/pkg/protocols/javascript/js.go
> +					fmt.Printf("canceling\n")
same here

2023-09-25 17:22 UTC, ehsandeep approved these changes

2023-09-26 11:24 UTC, Ice3man543 approved these changes

2023-09-26 11:25 UTC, merged