nuclei v3 bug fixes
projectdiscovery/nuclei pull request #4176
Opened 2023-09-21 20:54 UTC by tarunKoyalwar

## Proposed changes

- generate ecdsa key-pair for signing templates if none exist
- default key-pair are saved / retrieved from nuclei config folder
- fixed trailing whitespace in code protocol response exports

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-09-21 20:55 UTC, tarunKoyalwar commented
### example multiprotocol template

```yaml
id: multi-proto-example-code

info:
  name: multi-proto-example-code
  author: pdteam
  severity: info
  description: |
    multi protocol example using code and http protocol


code:
  - engine: 
      - sh
      - bash
    source: |
      echo "hello from code" | base64 


http:
  - raw:
      - |
        GET /?param={{code_response}} HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
    
    matchers:
      - type: status
        status:
          - 200
# digest: 4b0a00483046022100c060a867912857a78e261df8fec20d879bc06a00b72305823e136dc0f3de8470022100b001a80a51081cb8c097097d8ba28b1fdc4c76e1ab745375e55677cf0f337b84
```

2023-09-22 16:56 UTC, tarunKoyalwar commented
### TODO

- [ ] review should we keep `stdout` when `response` already exists
- [ ] add missing docs related to args etc

2023-10-01 16:39 UTC, tarunKoyalwar commented
### Signing templates by setting public/private keys in enviornment variable (POC)

```console
# set env variables
export NUCLEI_SIGNATURE_PRIVATE_KEY=$(cat $HOME/.config/nuclei/nuclei-template-signer)
export NUCLEI_SIGNATURE_PUBLIC_KEY=$(cat $HOME/.config/nuclei/nuclei-template-signer.pub)
export NUCLEI_SIGNATURE_ALGORITHM=$(cat $HOME/.config/nuclei/nuclei-template-signer.algo)

# move backup keys
cd  $HOME/.config/nuclei && mkdir backup && mv nuclei-template-* backup

# verify keys are not present in default dir
la $HOME/.config/nuclei | grep "nuclei"

# sign example template
./nuclei -t code.yaml -v -sign
[INF] All templates signatures were elaborated success=1 failed=0
```

2023-10-04 16:18 UTC, tarunKoyalwar commented
## User experience using signed and unsigned templates

```console
$ ./nuclei -t ~/nuclei-templates/http -sign -v
[INF] Generating new key-pair for signing code templates
[*] Enter User/Organization Name (exit to abort) : ProjectDiscovery.io
[*] Enter passphrase (exit to abort): 
[*] Enter same passphrase again: 
[INF] Successfully generated new key-pair for signing code templates


$ ./nuclei -t ~/nuclei-templates/http -sign -v
[INF] All templates signatures were elaborated success=6464 failed=0


$  ./nuclei         
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.0-dev

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.0.0-dev (development)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 6895
[INF] Executing 6219 signed templates from 'ProjectDiscovery.io'
[WRN] Executing 687 unsigned templates. Use with caution
[INF] No results found. Better luck next time!
```

2023-10-04 19:05 UTC, tarunKoyalwar commented
### New Changes

- detailed docs about signing templates and related changes are available at https://github.com/projectdiscovery/nuclei/blob/b90f629547ff2e2db7ec68e10f6a5d9c53202d20/docs/template-guide/code.mdx#L23-L143

### TBD

- discussion and user experience of re-signing of code protocol
- hardning mass signing of code protocol templates

2023-10-05 06:46 UTC, Mzack9999 approved these changes

2023-10-08 16:20 UTC, tarunKoyalwar commented
## example code template

```yaml
id: simple-code

info:
  name: simple-code
  author: pdteam
  severity: info
  tags: code
  description: |
    simple-code

code:
  - engine:
      - py
      - python3
    source: |
      import sys
      print("hello from code s" + sys.stdin.read())
    
    matchers:
      - type: word
        words:
          - "hello from code"
```

### when template does not have any digest/signature
```console
./nuclei -u scanme.sh -t simple-code.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.0-dev

		projectdiscovery.io

[WRN] Found 1 unverified templates (carefully examine the template before using it and use -sign flag to sign them)
[INF] Current nuclei version: v3.0.0-dev (development)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[WRN] Executing 1 unsigned templates. Use with caution
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
```
### signing a template
```console
$ ./nuclei -u scanme.sh -t simple-code.yaml -sign                  
[INF] All templates signatures were elaborated success=1 failed=0
```
### auto-verification of signed template before executing
```console
./nuclei -u scanme.sh -t simple-code.yaml      

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.0-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.0.0-dev (development)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from 'tarun'
[INF] Targets loaded for current scan: 1
[simple-code] [code] [info] scanme.sh
```
### when template content is modified template is considered as not verified template
```console
./nuclei -u scanme.sh -t simple-code.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.0-dev

		projectdiscovery.io

[WRN] Found 1 unverified templates (carefully examine the template before using it and use -sign flag to sign them)
[INF] Current nuclei version: v3.0.0-dev (development)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[WRN] Executing 1 unsigned templates. Use with caution
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
```

### re-signing code template if fragment matches with current user/signer
```
$ ./nuclei -u scanme.sh -t simple-code.yaml -sign                   
[INF] All templates signatures were elaborated success=1 failed=0
```


## re-signing of code templates when fragment is not present or does not belong to current signer/user
example template
```yaml
id: simple-code

info:
  name: simple-code
  author: pdteam
  severity: info
  tags: code
  description: |
    simple-code

code:
  - engine:
      - py
      - python3
    source: |
      import sys
      print("hello from code" + sys.stdin.read())
    
    matchers:
      - type: word
        words:
          - "hello from code"
# digest: 4a0a0047304502207cc624edaa99107f1a4b68ad246e3e48e888735cfde4f8882c4d72a5a98009d40221009ef1b4590ebeaee24d60d8485758e3711cba88c2a3eada7c2a7e18f82afb4393:abacus
```

**in this case even if user tries to re-sign code protocol template then it is not allowed as fragment does not match**
**this means user is trying to sign a code protocol template that does not belong to user without viewing which is discouraged**
this can be considered as a security bump to discourage mass signing of templates with code protocol without actually verfiying them visually . 

```console
$ ./nuclei -u scanme.sh -t simple-code.yaml -v -sign                
[ERR] could not sign 'simple-code.yaml': [signer:RUNTIME] fragment mismatch: expected '73812c4e0e52692225979bd2d5f05a3c' got 'abacus'
[INF] All templates signatures were elaborated success=0 failed=1
```

to resolve this situation user needs to manually remove digest from template

2023-10-11 12:38 UTC, ehsandeep requested changes
- [ ] printing issues when running workflows
- [ ] printing issue with non-yaml files (`.yaml`) when used with `-sign` option
- [ ] printing issue with counter display with workflows for unsigned templates

2023-10-12 19:53 UTC, tarunKoyalwar commented
```console
$ ./nuclei                                                          

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.0-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.0.0-dev (development)
[INF] Current nuclei-templates version: v9.6.5 (latest)
[INF] New templates added in latest release: 75
[INF] Templates loaded for current scan: 6967
[INF] Executing 6978 signed templates from tarunKoyalwar
[INF] No results found. Better luck next time!
```

2023-10-12 19:57 UTC, tarunKoyalwar commented
@ehsandeep  it will show 1 unsigned template because in nuclei file extension filtering is case-sensitive and looks like there is a template in nuclei-templates repo (only 1) that has `.YAML` as extension instead of usual `.yaml` (ref: https://github.com/projectdiscovery/nuclei-templates/blob/main/file/nodejs/xss-disable-mustache-escape.YAML)

when renamed to `.yaml` there will be no unsigned templates as shown in above example

2023-10-13 07:46 UTC, ehsandeep approved these changes

2023-10-13 07:47 UTC, merged