introduce exclude target flag
projectdiscovery/nuclei pull request #4214
Opened 2023-10-03 09:49 UTC by dogancanbakir

Closes #3877.

```console
$ cat targets.txt 
1.1.1.1
status.example.com
1.1.1.1/24
*.gov
admin*.gov

$ go run . -l list.txt -etg 1.1.1.1/24

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.15

                projectdiscovery.io

[INF] Excluding target from target list: {"input":"1.1.1.0"}
[INF] Excluding target from target list: {"input":"1.1.1.1"}
[INF] Excluding target from target list: {"input":"1.1.1.2"}
[INF] Excluding target from target list: {"input":"1.1.1.3"}
[INF] Excluding target from target list: {"input":"1.1.1.4"}
[INF] Excluding target from target list: {"input":"1.1.1.5"}
[INF] Excluding target from target list: {"input":"1.1.1.6"}
[INF] Excluding target from target list: {"input":"1.1.1.7"}
[INF] Excluding target from target list: {"input":"1.1.1.8"}
[INF] Excluding target from target list: {"input":"1.1.1.9"}
[INF] Excluding target from target list: {"input":"1.1.1.10"}
[INF] Excluding target from target list: {"input":"1.1.1.11"}
[INF] Excluding target from target list: {"input":"1.1.1.12"}
[INF] Excluding target from target list: {"input":"1.1.1.13"}
[INF] Excluding target from target list: {"input":"1.1.1.14"}
[INF] Excluding target from target list: {"input":"1.1.1.15"}
[INF] Excluding target from target list: {"input":"1.1.1.16"}
[INF] Excluding target from target list: {"input":"1.1.1.17"}
[INF] Excluding target from target list: {"input":"1.1.1.18"}
[INF] Excluding target from target list: {"input":"1.1.1.19"}
[INF] Excluding target from target list: {"input":"1.1.1.20"}
[INF] Excluding target from target list: {"input":"1.1.1.21"}
[INF] Excluding target from target list: {"input":"1.1.1.22"}
[INF] Excluding target from target list: {"input":"1.1.1.23"}
[INF] Excluding target from target list: {"input":"1.1.1.24"}
[INF] Excluding target from target list: {"input":"1.1.1.25"}
[INF] Excluding target from target list: {"input":"1.1.1.26"}
[INF] Excluding target from target list: {"input":"1.1.1.27"}
[INF] Excluding target from target list: {"input":"1.1.1.28"}
[INF] Excluding target from target list: {"input":"1.1.1.29"}
[INF] Excluding target from target list: {"input":"1.1.1.30"}
[INF] Excluding target from target list: {"input":"1.1.1.31"}
[INF] Excluding target from target list: {"input":"1.1.1.32"}
[INF] Excluding target from target list: {"input":"1.1.1.33"}
[INF] Excluding target from target list: {"input":"1.1.1.34"}
[INF] Excluding target from target list: {"input":"1.1.1.35"}
[INF] Excluding target from target list: {"input":"1.1.1.36"}
[INF] Excluding target from target list: {"input":"1.1.1.37"}
[INF] Excluding target from target list: {"input":"1.1.1.38"}
[INF] Excluding target from target list: {"input":"1.1.1.39"}
[INF] Excluding target from target list: {"input":"1.1.1.40"}
[INF] Excluding target from target list: {"input":"1.1.1.41"}
[INF] Excluding target from target list: {"input":"1.1.1.42"}
[INF] Excluding target from target list: {"input":"1.1.1.43"}
[INF] Excluding target from target list: {"input":"1.1.1.44"}
[INF] Excluding target from target list: {"input":"1.1.1.45"}
[INF] Excluding target from target list: {"input":"1.1.1.46"}
[INF] Excluding target from target list: {"input":"1.1.1.47"}
[INF] Excluding target from target list: {"input":"1.1.1.48"}
[INF] Excluding target from target list: {"input":"1.1.1.49"}
[INF] Excluding target from target list: {"input":"1.1.1.50"}
[INF] Excluding target from target list: {"input":"1.1.1.51"}
[INF] Excluding target from target list: {"input":"1.1.1.52"}
[INF] Excluding target from target list: {"input":"1.1.1.53"}
[INF] Excluding target from target list: {"input":"1.1.1.54"}
[INF] Excluding target from target list: {"input":"1.1.1.55"}
[INF] Excluding target from target list: {"input":"1.1.1.56"}
[INF] Excluding target from target list: {"input":"1.1.1.57"}
[INF] Excluding target from target list: {"input":"1.1.1.58"}
[INF] Excluding target from target list: {"input":"1.1.1.59"}
[INF] Excluding target from target list: {"input":"1.1.1.60"}
[INF] Excluding target from target list: {"input":"1.1.1.61"}
[INF] Excluding target from target list: {"input":"1.1.1.62"}
[INF] Excluding target from target list: {"input":"1.1.1.63"}
[INF] Excluding target from target list: {"input":"1.1.1.64"}
[INF] Excluding target from target list: {"input":"1.1.1.65"}
[INF] Excluding target from target list: {"input":"1.1.1.66"}
[INF] Excluding target from target list: {"input":"1.1.1.67"}
[INF] Excluding target from target list: {"input":"1.1.1.68"}
[INF] Excluding target from target list: {"input":"1.1.1.69"}
[INF] Excluding target from target list: {"input":"1.1.1.70"}
[INF] Excluding target from target list: {"input":"1.1.1.71"}
[INF] Excluding target from target list: {"input":"1.1.1.72"}
[INF] Excluding target from target list: {"input":"1.1.1.73"}
[INF] Excluding target from target list: {"input":"1.1.1.74"}
[INF] Excluding target from target list: {"input":"1.1.1.75"}
[INF] Excluding target from target list: {"input":"1.1.1.76"}
[INF] Excluding target from target list: {"input":"1.1.1.77"}
[INF] Excluding target from target list: {"input":"1.1.1.78"}
[INF] Excluding target from target list: {"input":"1.1.1.79"}
[INF] Excluding target from target list: {"input":"1.1.1.80"}
[INF] Excluding target from target list: {"input":"1.1.1.81"}
[INF] Excluding target from target list: {"input":"1.1.1.82"}
[INF] Excluding target from target list: {"input":"1.1.1.83"}
[INF] Excluding target from target list: {"input":"1.1.1.84"}
[INF] Excluding target from target list: {"input":"1.1.1.85"}
[INF] Excluding target from target list: {"input":"1.1.1.86"}
[INF] Excluding target from target list: {"input":"1.1.1.87"}
[INF] Excluding target from target list: {"input":"1.1.1.88"}
[INF] Excluding target from target list: {"input":"1.1.1.89"}
[INF] Excluding target from target list: {"input":"1.1.1.90"}
[INF] Excluding target from target list: {"input":"1.1.1.91"}
[INF] Excluding target from target list: {"input":"1.1.1.92"}
[INF] Excluding target from target list: {"input":"1.1.1.93"}
[INF] Excluding target from target list: {"input":"1.1.1.94"}
[INF] Excluding target from target list: {"input":"1.1.1.95"}
[INF] Excluding target from target list: {"input":"1.1.1.96"}
[INF] Excluding target from target list: {"input":"1.1.1.97"}
[INF] Excluding target from target list: {"input":"1.1.1.98"}
[INF] Excluding target from target list: {"input":"1.1.1.99"}
[INF] Excluding target from target list: {"input":"1.1.1.100"}
[INF] Excluding target from target list: {"input":"1.1.1.101"}
[INF] Excluding target from target list: {"input":"1.1.1.102"}
[INF] Excluding target from target list: {"input":"1.1.1.103"}
[INF] Excluding target from target list: {"input":"1.1.1.104"}
[INF] Excluding target from target list: {"input":"1.1.1.105"}
[INF] Excluding target from target list: {"input":"1.1.1.106"}
[INF] Excluding target from target list: {"input":"1.1.1.107"}
[INF] Excluding target from target list: {"input":"1.1.1.108"}
[INF] Excluding target from target list: {"input":"1.1.1.109"}
[INF] Excluding target from target list: {"input":"1.1.1.110"}
[INF] Excluding target from target list: {"input":"1.1.1.111"}
[INF] Excluding target from target list: {"input":"1.1.1.112"}
[INF] Excluding target from target list: {"input":"1.1.1.113"}
[INF] Excluding target from target list: {"input":"1.1.1.114"}
[INF] Excluding target from target list: {"input":"1.1.1.115"}
[INF] Excluding target from target list: {"input":"1.1.1.116"}
[INF] Excluding target from target list: {"input":"1.1.1.117"}
[INF] Excluding target from target list: {"input":"1.1.1.118"}
[INF] Excluding target from target list: {"input":"1.1.1.119"}
[INF] Excluding target from target list: {"input":"1.1.1.120"}
[INF] Excluding target from target list: {"input":"1.1.1.121"}
[INF] Excluding target from target list: {"input":"1.1.1.122"}
[INF] Excluding target f [...]

2023-10-04 07:18 UTC, mnafees commented
Hi @ehsandeep @tarunKoyalwar, we would like to use this feature and I can volunteer to review this PR, if that is something that's possible.

2023-10-04 09:52 UTC, ehsandeep requested changes
- [ ] Display counter in single line instead of list of each

```console
[INF] Excluded target from input list: 80
```
- [ ] Notes to add in docs
	- Exclude target process input per line as it is.
	- Exclude target does not resolve hostname to exclude ip.

2023-10-04 16:45 UTC, ehsandeep approved these changes
```console
echo 1.1.1.1/24 | ./nuclei -id ptr-fingerprint -eh exclude.txt 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.15

		projectdiscovery.io

[INF] Number of hosts excluded from input: 10
[INF] Current nuclei version: v2.9.15 (latest)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 246
[INF] No results found. Better luck next time!
```

2023-10-09 14:35 UTC, tarunKoyalwar requested changes
current implementation of CIDR / IP lgtm ! proposing following changes instead of doing a exact match on target domains/urls
ex:
### this works
```console
$ echo "hackerone.com" | ./nuclei -eh hackerone.com                                             1 ↵

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.15

		projectdiscovery.io

[INF] Number of hosts excluded from input: 1
[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v2.9.15 (latest)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 6895
[INF] No results found. Better luck next time!
```

### this does not 

```console
$ echo "https://hackerone.com" | ./nuclei -eh hackerone.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.15

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v2.9.15 (latest)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 6895
[INF] Targets loaded for current scan: 2
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 1195 (Reduced 2268 Requests)
[dnssec-detection] [dns] [info] hackerone.com
[mx-service-detector:Google Apps] [dns] [info] hackerone.com
```
```console
$ echo "hackerone.com" | ./nuclei -eh https://hackerone.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.15

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v2.9.15 (latest)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 6895
[INF] Targets loaded for current scan: 2
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 1195 (Reduced 2268 Requests)
[nameserver-fingerprint] [dns] [info] hackerone.com [a.ns.hackerone.com.,b.ns.hackerone.com.]
```

## proposed changes / discussion
- [x] perform exclusion of hosts after uncover output ( i think this will be needed in near future)
- [ ] since the flag is `-eh exclude hosts` . exclusion of targets should be done based on Host value i.e (hostname:port) and not urls . current implementation only supports exact match
- [ ] i think we should have different methods for remove and add instead of having a common `processValue` since we might get a enhancement issue soon asking for `wildcard exclusion support` . if we have different methods there won't be any need of refactor and  wildcard functionality would be easy to implement in future
- [ ] Incorrect target count  during exclusion, check `this does not` section , it counts exclusion host as a target
```
[INF] Targets loaded for current scan: 2
```

what do you think ? cc: @dogancanbakir  @ehsandeep

2023-11-05 11:01 UTC, ehsandeep requested changes
Merge conflict + comments from @dogancanbakir

2023-11-08 07:36 UTC, dogancanbakir commented
FYI, will review, maybe refactor the code and then proceed with adding the new feature.

2023-11-21 15:28 UTC, tarunKoyalwar reviewed
implementation lgtm ! suggested a change regarding potential duplicated code

```console
$ echo "hackerone.com" | ./nuclei -eh hackerone.com             

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.3

		projectdiscovery.io

[INF] Number of hosts excluded from input: 1
[INF] Current nuclei version: v3.0.3 (outdated)
[INF] Current nuclei-templates version: v9.6.9 (latest)
[INF] New templates added in latest release: 73
[INF] Templates loaded for current scan: 7278
[INF] Executing 5264 signed templates from projectdiscovery/nuclei-templates
[WRN] Executing 2028 unsigned templates. Use with caution.
[INF] No results found. Better luck next time!
```
## More Changes

we have a exported/public method in `Input` struct `i.Set(item)` which when used bypasses exclution hosts list hence Suggesting addition of  new method 
```
func (i*Input) SetWithExclusions(target string)
```
^ alternative method to `i.Set(target)` exported method which does not add target to store if given target is already blacklisted/excluded

we use `i.Set(item)` in runner and we can replace it with `i.SetWithExclusions(item)`

2023-11-21 15:28 UTC, tarunKoyalwar commented on pkg/core/inputs/hybrid/hmap.go
> +		metaInput := &contextargs.MetaInput{Input: target}
i think we have duplicated implementation of adding values to store in using addTargets. we can just do 
```go
func (i *Input) addTargets(targets []string) {
   for _ target := targets {
       i.Set(item)
    }
}
```

2023-11-23 08:53 UTC, ehsandeep reviewed
```console
echo "https://hackerone.com" | ./nuclei -eh hackerone.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.3

		projectdiscovery.io

panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/core/inputs/hybrid.(*Input).delItem.func1({0x1400005c360, 0x22, 0x8?}, {0x14000d694d7?, 0x1?, 0x1?})
	/Users/geekboy/Github/nuclei/pkg/core/inputs/hybrid/hmap.go:441 +0xec
github.com/projectdiscovery/hmap/store/disk.(*LevelDB).Scan(0x14000a2cea8?, {{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, 0x14000ea64f8})
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/hmap@v0.0.24/store/disk/leveldb.go:224 +0x1e0
github.com/projectdiscovery/hmap/store/hybrid.(*HybridMap).Scan(0x14000b2bed0?, 0xd?)
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/hmap@v0.0.24/store/hybrid/hybrid.go:258 +0xe4
github.com/projectdiscovery/nuclei/v3/pkg/core/inputs/hybrid.(*Input).delItem(0x1400068f500, 0xd?)
	/Users/geekboy/Github/nuclei/pkg/core/inputs/hybrid/hmap.go:425 +0xe4
github.com/projectdiscovery/nuclei/v3/pkg/core/inputs/hybrid.(*Input).Del(0x1400068f500, {0x14000b2bed0, 0xd})
	/Users/geekboy/Github/nuclei/pkg/core/inputs/hybrid/hmap.go:393 +0x5dc
github.com/projectdiscovery/nuclei/v3/pkg/core/inputs/hybrid.(*Input).initializeInputSources(0x0?, 0x14000d69cf8)
	/Users/geekboy/Github/nuclei/pkg/core/inputs/hybrid/hmap.go:181 +0x410
github.com/projectdiscovery/nuclei/v3/pkg/core/inputs/hybrid.New(0x14000d69cf8)
	/Users/geekboy/Github/nuclei/pkg/core/inputs/hybrid/hmap.go:91 +0x33c
github.com/projectdiscovery/nuclei/v3/internal/runner.New(0x104936d80)
	/Users/geekboy/Github/nuclei/internal/runner/runner.go:218 +0x820
main.main()
	/Users/geekboy/Github/nuclei/cmd/nuclei/main.go:119 +0x340
```

2023-11-23 10:55 UTC, ehsandeep approved these changes
@dogancanbakir we can create follow up ticket for regex support to cover cases like wildcard based exclusion.

2023-11-23 11:02 UTC, dogancanbakir commented
For regex support, https://github.com/projectdiscovery/nuclei/issues/4412

2023-11-23 18:34 UTC, tarunKoyalwar approved these changes
LGTM !

2023-11-23 18:35 UTC, merged