Add endpoint var
projectdiscovery/nuclei pull request #4283
Opened 2023-10-23 10:42 UTC by dogancanbakir

## Proposal
Define a simple `IpPort` variable (or similar name) that points to the actual `ip|domain:port` without ambiguity and "deprecate" or disincentive `Hostname` and `Host` usage, unless necessary. Closes #3954.

```console
$ cat test.txt 
192.168.5.1:443
192.168.1.1

$ cat test.yaml 
id: test

info:
  name: test
  author: test
  severity: info
  tags: test

tcp:
    - host:
      - "{{Endpoint}}"
      port: 443
      matchers:
        - type: dsl
          dsl:
            - "jarm(Hostname) == 'xxxxxx'"

$ cat test.txt | go run . -t test.yaml -verbose

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.1

                projectdiscovery.io

[INF] Current nuclei version: v3.0.1 (latest)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] New templates added in latest release: 1
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 2
[VER] Sent TCP request to 192.168.1.1:443
[WRN] [test] Could not make network request for (192.168.5.1:443) : could not connect to server: [:RUNTIME] ztls fallback failed <- dial tcp 192.168.5.1:443: i/o timeout
[INF] No results found. Better luck next time!
```

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-10-23 13:34 UTC, Mzack9999 requested changes

2023-10-23 13:34 UTC, Mzack9999 commented on pkg/protocols/utils/variables.go
> +		return fmt.Sprintf("%s:%s", hostname, port)
I think https://pkg.go.dev/net#JoinHostPort is preferred as it escapes correctly ipv6s

2023-10-23 14:19 UTC, Mzack9999 approved these changes

2024-02-10 09:01 UTC, ehsandeep commented
Closing this, since now port input now moved into seprate field.

2024-02-10 09:01 UTC, closed without merging