restructure repo dir
projectdiscovery/nuclei pull request #4293
Opened 2023-10-25 13:32 UTC by dogancanbakir

## Proposed changes
Note: what about simply cloning to destination-base-folder/repo-owner/repo-name literally as in GitHub

Closes #3925.

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-10-26 13:52 UTC, ehsandeep reviewed
```console
--- FAIL: TestDownloadCustomTemplatesFromGitHub (41.06s)
    github_test.go:33: 
        	Error Trace:	/home/runner/work/nuclei/nuclei/pkg/external/customtemplates/github_test.go:33
        	Error:      	unable to find file "/tmp/template-custom-2556226393/github/nuclei-templates-projectdiscovery"
        	Test:       	TestDownloadCustomTemplatesFromGitHub
        	Messages:   	cloned directory does not exists
```

2023-10-28 10:31 UTC, tarunKoyalwar requested changes
newly installed templates are created on correct path . but migration/sync of old dir to new dir doesn't seem to be working 

```console
$  GITHUB_TEMPLATE_REPO="tarunKoyalwar/nuclei-templates" ./nuclei -ut

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.1

		projectdiscovery.io

[INF] No new updates found for nuclei templates
[INF] Repo tarunKoyalwar/nuclei-templates cloned successfully at /Users/tarun/nuclei-templates/github/tarunKoyalwar/nuclei-templates
```

```console
$  ls
tarunKoyalwar                  tarunKoyalwar-nuclei-templates
```

2023-10-30 10:36 UTC, tarunKoyalwar approved these changes
lgtm !

>seems like there was some issue with my nuclei templates dir . fresh reinstall solved the issue

```console
$  GITHUB_TEMPLATE_REPO="ehsandeep/nuclei-templates" ./nuclei -ut -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.1

		projectdiscovery.io

[INF] No new updates found for nuclei templates
[ERR] ehsandeep/nuclei-templates: already up-to-date
```

```console
$ la
total 0
drwxr-xr-x  31 tarun  staff   992B Oct 30 16:00 nuclei-templates-ehsandeep
$  la
total 0
drwxr-xr-x  3 tarun  staff    96B Oct 30 16:02 ehsandeep
```

2023-10-30 15:30 UTC, ehsandeep approved these changes

2023-10-30 15:30 UTC, merged