add additional json fields: port,ip,scheme,url
projectdiscovery/nuclei pull request #4417
Opened 2023-11-24 14:52 UTC by tarunKoyalwar

2023-11-25 19:40 UTC, dogancanbakir approved these changes
LGTM

2023-11-27 08:44 UTC, ehsandeep requested changes
return `host` as `ip` when only ip is available

2023-11-27 14:20 UTC, tarunKoyalwar commented
```console
$ echo 128.199.158.128 | ./nuclei -id tech-detect -ms -j -silent | jq .
{
  "template": "http/technologies/tech-detect.yaml",
  "template-url": "https://templates.nuclei.sh/public/tech-detect",
  "template-id": "tech-detect",
  "template-path": "/Users/tarun/nuclei-templates/http/technologies/tech-detect.yaml",
  "info": {
    "name": "Wappalyzer Technology Detection",
    "author": [
      "hakluke"
    ],
    "tags": [
      "tech"
    ],
    "severity": "info",
    "metadata": {
      "max-request": 1
    }
  },
  "type": "http",
  "host": "128.199.158.128",
  "port": "443",
  "scheme": "https",
  "url": "https://128.199.158.128",
  "request": "GET / HTTP/1.1\r\nHost: 128.199.158.128\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2866.71 Safari/537.36\r\nConnection: close\r\nAccept: */*\r\nAccept-Language: en\r\nAccept-Encoding: gzip\r\n\r\n",
  "response": "HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Length: 2\r\nContent-Type: text/plain; charset=utf-8\r\nDate: Mon, 27 Nov 2023 14:19:25 GMT\r\n\r\nok",
  "ip": "128.199.158.128",
  "timestamp": "2023-11-27T19:49:25.221005+05:30",
  "matcher-status": false
```

2023-11-28 08:56 UTC, ehsandeep approved these changes

2023-11-28 08:56 UTC, merged