Adding an option to dump resume files when a runner hangs
projectdiscovery/nuclei pull request #4440
Opened 2023-11-29 01:08 UTC by wk8

## Proposed changes

When a runner hangs, it can be very handy to be able to resume it from where it crashed.

This patch adds a new option to dump a resume file from the runner, on top of the stacktrace.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-11-29 17:17 UTC, wk8 commented
@Mzack9999 would appreciate a review on this one as well, thanks a lot :)

2023-12-26 11:26 UTC, wk8 commented
@Mzack9999 any chance you could have a look? Thanks so much! :)

2023-12-26 13:28 UTC, dogancanbakir approved these changes
LGTM

2023-12-26 13:28 UTC, dogancanbakir commented on pkg/utils/monitor/monitor.go
> +// Callbacks should only be
Finish the sentence please

2023-12-28 07:51 UTC, wk8 commented on pkg/utils/monitor/monitor.go
> +// Callbacks should only be
My bad, removed.

2023-12-28 08:27 UTC, wk8 commented
Thanks for the review @dogancanbakir ! Amended as requested :)

2023-12-28 18:34 UTC, ehsandeep requested changes
@wk8 thanks for the PR, we can enable this behavior with existing option `-hm, -hang-monitor` only as it's generally useful and to avoid additional option for it.

2024-01-12 20:03 UTC, tarunKoyalwar commented
### New Updates

- now resume file is always created on hang monitor crash exit (cc: @ehsandeep )

2024-01-12 20:16 UTC, ehsandeep approved these changes

2024-01-12 20:16 UTC, merged