nil check
projectdiscovery/nuclei pull request #4511
Opened 2023-12-19 05:33 UTC by dogancanbakir

## Proposed changes

Closes #4504

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2023-12-20 07:20 UTC, tarunKoyalwar requested changes
this will fix the panic but i think underlying issue will still remain as compiled operators should never be nil ( when template is compiled while loading, matchers and extractors are compiled and put in operators )

logging it using gologger might not be enough for cloud/sdk use cases . i think we should ask & wait for actual command / template to reproduce this

cc: @ehsandeep

2023-12-20 07:24 UTC, dogancanbakir commented
@tarunKoyalwar,
>  i think we should ask & wait for actual command / template to reproduce this

I was thinking the same; somehow, I forgot to ask for the command, but I think the nil check should be there anyway.

2024-01-12 19:44 UTC, tarunKoyalwar approved these changes
lgtm !

@dogancanbakir , looks like user who reported issue is not available and looks like it will be difficult to locate this on bulk scans so added a defer recover and modified error statement to include template-id . 

I think this should be enough to avoid panic and later on when user finds this scenario again we will have template-id to locate the core issue

2024-01-12 21:54 UTC, ehsandeep approved these changes

2024-01-12 21:54 UTC, merged