include params
projectdiscovery/nuclei pull request #4894
Opened 2024-03-15 15:42 UTC by dogancanbakir

## Proposed changes

Closes #4553

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-03-22 13:08 UTC, tarunKoyalwar requested changes
@dogancanbakir , if i am not wrong , according to this change and based on reported issue this will add query params to BaseURL . while that would be great , this breaks existing templates . see

https://github.com/projectdiscovery/nuclei-templates/blob/3fcda12c44c235e09586fd929c37fa60fbe28f71/http/cves/2018/CVE-2018-9161.yaml#L30-L35

lot of templates are written in format

```yaml
{{Baseurl}}/mypath/to/exploit?abc
```
and we parse url after replacing BaseURL here with input we got , if query params is included now it might break existing ones 

to keep query params as well in http templates we have introduced concept called automerge params . which automerges params obtained from target to template urls after parsing .

maybe we can do the same here 

also i think just in case it might be good to add new variable called `Query` which contains encode params (including `?` ) if any 
cc: @ehsandeep

2024-03-22 15:25 UTC, tarunKoyalwar commented
### TODO
- [ ] Pass raw input obtained using ctx.MetaInput.Input to `Input` variable , currently we pass this value as stdin in code protocol , but we can pass this value to `Input` variable and make it standard across all protocols

2024-04-09 14:46 UTC, tarunKoyalwar approved these changes
lgtm !

> 10. Query => ?path=xyz&test=param

```console
$ ./nuclei -id tech-detect -u 'https://scanme.sh/?path=xyz&test=param' -v -svd

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.0

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[WRN] Excluded 114 template[s] with known weak matchers / tags excluded from default run using .nuclei-ignore
[INF] Current nuclei version: v3.2.0 (outdated)
[INF] Current nuclei-templates version: v9.8.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 77
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[DBG] HTTP Protocol request variables: 
	1. BaseURL => https://scanme.sh/
	2. DN => scanme
	3. FQDN => scanme.sh
	4. File => /
	5. Host => scanme.sh
	6. Hostname => scanme.sh
	7. Input => https://scanme.sh/
	8. Path => /
	9. Port => 443
	10. Query => ?path=xyz&test=param
	11. RDN => scanme.sh
	12. RootURL => https://scanme.sh
	13. SD => 
	14. Scheme => https
	15. TLD => sh
	16. ip => 

[VER] [tech-detect] Sent HTTP request to https://scanme.sh/?path=xyz&test=param
[DBG] Http Protocol response variables: 
	1. BaseURL => https://scanme.sh/
	2. DN => scanme
	3. FQDN => scanme.sh
	4. File => /
	5. Host => scanme.sh
	6. Hostname => scanme.sh
	7. Input => https://scanme.sh/
	8. Path => /
	9. Port => 443
	10. Query => ?path=xyz&test=param
	11. RDN => scanme.sh
	12. RootURL => https://scanme.sh
	13. SD => 
	14. Scheme => https
	15. TLD => sh
	16. all_headers => HTTP/1.1 200 OK  Connecti .... Apr 2024 14:45:21 GMT    
	17. body => ok
	18. content_length => 2
	19. content_type => text/plain; charset=utf-8
	20. curl-command => curl -X 'GET' -H 'Accept: .... .sh/?path=xyz&test=param'
	21. date => Tue, 09 Apr 2024 14:45:21 GMT
	22. duration => 0.687869041
	23. header => HTTP/1.1 200 OK  Connecti .... Apr 2024 14:45:21 GMT    
	24. host => https://scanme.sh/?path=xyz&test=param
	25. interactsh-server => 
	26. ip => 128.199.158.128
	27. matched => https://scanme.sh/?path=xyz&test=param
	28. request => GET /?path=xyz&test=param .... Accept-Encoding: gzip    
	29. response => HTTP/1.1 200 OK  Connecti .... r 2024 14:45:21 GMT    ok
	30. status_code => 200
	31. template-id => tech-detect
	32. template-info => {Wappalyzer Technology De .... ap[max-request:1] <nil> }
	33. template-path => /Users/tarun/nuclei-templ .... nologies/tech-detect.yaml
	34. type => http

[INF] No results found. Better luck next time!
```

2024-04-23 13:47 UTC, ehsandeep approved these changes

2024-04-23 13:47 UTC, merged