feat: added auto proxy based test generation for templates
projectdiscovery/nuclei pull request #5014
Opened 2024-04-08 11:15 UTC by Ice3man543

## Proposed changes

Closes #4996

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-04-17 13:56 UTC, dogancanbakir approved these changes
lgtm -left -optional- comments

2024-04-17 13:56 UTC, dogancanbakir commented on cmd/nuclei/main.go
> +		flagSet.BoolVarP(&options.RunNucleiTests, "run-tests", "rts", false, "run generated nuclei test-cases"),
We can rename it to something more descriptive, such as RunAutoGeneratedTests or RunTemplateTests

2024-04-17 13:56 UTC, dogancanbakir commented on internal/runner/runner.go
> +	if len(store.Templates()) > 1 && r.options.AutogenerateTests {
We can also check whether the given template is http or not.

2024-06-10 23:24 UTC, ehsandeep requested changes
merge conflict

2025-10-08 09:50 UTC, dogancanbakir commented
bump

2025-11-25 04:09 UTC, dogancanbakir commented
merge conflict

2026-02-05 10:29 UTC, tarunKoyalwar commented
outdated , probably we can revisit ?

2026-05-31 00:21 UTC, closed without merging