Moving failure check past interactsh eviction
projectdiscovery/nuclei pull request #5029
Opened 2024-04-10 21:18 UTC by Mzack9999

## Proposed changes
Cherry picking interactsh hotfix for #4980 from #5018 via yet another callback (deferred failure write to the very end based on the reasoning that matching are impossible post eviction)

## Checklist
- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-04-11 20:54 UTC, tarunKoyalwar requested changes
- looks like '{{interactsh-url}}' markers used in payloads are not getting matched [ both directly in payloads or by referencing from variables ]

```yaml
id: interactsh-stop-at-first-match-integration-test

info:
  name: Interactsh StopAtFirstMatch Integration Test
  author: pdteam
  severity: info

variables:
  oast: "{{interactsh-url}}"

http:
  - raw:
      - |
        GET /{{data}} HTTP/1.1
        Host: {{BaseURL}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate
        Connection: close
        Upgrade-Insecure-Requests: 1
        Cache-Control: max-age=0

    payloads:
      data:
        - "{{oast}}"
        - "1"
        - "2"
        - "3"
        - "4"

    stop-at-first-match: true

    matchers:
      - type: word
        part: interactsh_protocol # Confirms DNS Interaction
        words:
          - "dns"
```

```console
$  ./nuclei -u http://honey.scanme.sh -t a.yaml -v -interactions-cooldown-period 20

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.4

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.4 (latest)
[INF] Current nuclei-templates version: v9.8.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 77
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.online
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/1
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/3
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/2
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/4
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/coc4r9ko47mo1skqsn90spcowb3qbgyht.oast.online
[INF] No results found. Better luck next time!
```

> Note if we replace {{data}} marker with {{interactsh-url}} it is working , this seems to be issue specific to payloads !

2024-04-11 20:57 UTC, tarunKoyalwar commented
- Looks like this is also happening in main / latest

```console
$  nuclei -u http://honey.scanme.sh -t a.yaml -v -interactions-cooldown-period 20 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.4

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.4 (latest)
[INF] Current nuclei-templates version: v9.8.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 77
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.fun
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/1
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/4
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/3
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/2
[VER] [interactsh-stop-at-first-match-integration-test] Sent HTTP request to http://honey.scanme.sh/coc4saco47mo22ffnj90i3f7iueisetuk.oast.fun
[INF] No results found. Better luck next time!
```

2024-04-11 21:06 UTC, tarunKoyalwar commented
this feels like common ( interactsh + payloads ) ex: https://github.com/projectdiscovery/nuclei/issues/5020

looking at gcache , default cache size is 5000 items , and eviction is set to 60 sec. and the default response read size (in-memory is set to 10 MB) .

assuming worst case , if we are running fuzzing templates with payloads and have sent say 5000 requests < 1 min memory would spike from 1-50 GB ( could lead to oom kill maybe ) 

would it be better to use disk cache instead of gcache for requests ?? to handle such spikes , considering that interactsh hit rate would be very low in normal / real-world conditions 

cc: @Mzack9999

2024-04-12 00:20 UTC, Mzack9999 commented
I think the issue is because the interactsh handling is completely missing within the `nuclei/pkg/protocols/http/request.go`.`executeParallelHTTP(...)` and `.executeRaceRequest(...)` - I guess it got lost somehow during the implementation of `httputils.StopAtFirstMatchHandler`. Since this area appears to be quite unstable and problematic, I would suggest to disable threading and tackle callback related issues one by one as they appear. The solution here appears to be adding `interactsh.RequestEvent(...)` within the corresponding super-nested callback triggered from this component on the event using the payload with interactsh-url

2024-04-15 16:41 UTC, Mzack9999 commented
Introducing interactsh support within `race|parallell` http execution leads to further syncronism issues due to the scattered logic within callbacks. Differently from fuzzing, the requests are not cloned and isolated and the scoping of the `interactsh-url` might vary depending if it's defined per request, globally per request group and so on, leading to erroneous matchers evaluation.
For the time being I think the better option is the temporary patch of imposing unitary thread in case of payloads with interactsh, so that the code branch passes through the standard `request.ExecuteWithResults` which is battle tested.

2024-06-13 15:48 UTC, Mzack9999 commented
Closing for future heavier refactor

2024-06-13 15:48 UTC, closed without merging