Add `profile` option to load template profile
projectdiscovery/nuclei pull request #5125
Opened 2024-04-30 17:58 UTC by RamanaReddy0M

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-05-02 12:36 UTC, ehsandeep requested changes
- add profile list option
- issue with custom profile input

2024-05-02 13:10 UTC, dogancanbakir requested changes
missing ` -tpl, -profile-list               list community template profiles`

2024-05-02 13:18 UTC, dogancanbakir approved these changes

2024-05-04 16:12 UTC, ehsandeep approved these changes

2024-05-04 16:23 UTC, merged