feat: added fuzzing output enhancements
projectdiscovery/nuclei pull request #5126
Opened 2024-04-30 20:38 UTC by Ice3man543

## Proposed changes

Closes #4908 by implementing extra output for fuzzing results. Deduplication is a separate issue #4962 

<img width="1280" alt="Screenshot 2024-05-01 at 2 06 07 AM" src="https://github.com/projectdiscovery/nuclei/assets/22318055/2b132ff0-04d7-489f-84f2-fb123a1893f8">

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-05-01 10:32 UTC, Mzack9999 approved these changes

2024-05-01 18:59 UTC, tarunKoyalwar approved these changes

2024-05-03 11:00 UTC, ehsandeep requested changes
in multiple mode where we don't know which query parameter got matched, we print blank `query` result, which we can ignore from CLI output.

```
[generic-rfi] [http] [high] https://example.com/?x=https://rfi.nessus.org/rfi.txt&f=https://rfi.nessus.org/rfi.txt [query:] [GET]
```

2024-05-03 13:14 UTC, ehsandeep approved these changes

2024-05-03 13:16 UTC, merged