Fuzzing additions & enhancements (wip)
projectdiscovery/nuclei pull request #5139
Opened 2024-05-03 18:11 UTC by Ice3man543

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-05-04 15:59 UTC, ehsandeep requested changes
- [x] Misc format update:
```
[INF] [sqli-error-based] Fuzz points for http://127.0.0.1:8082/user [body:role] [POST]
```
- [x] allow path to break values by separator and fuzz each separately
- [x] allow part to be customizable with allow and deny and multiple values
- [ ] keep track of non matches and allow ignoring values which don't yield issues (example. path parameters after above change etc)

2024-05-07 11:02 UTC, Ice3man543 commented
- Added skipping of parameters after certain frequency of no issues found in nuclei fuzzing (hardcoded currently, TODO: Move to opts)

```console
❯ ./nuclei -l list.txt -t template.yaml -dast -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.5

                projectdiscovery.io

[INF] Supplied input was automatically deduplicated (1 removed).
[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.5 (outdated)
[INF] Current nuclei-templates version: v9.8.5 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 142
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 12
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/11
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/9'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/4'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/8
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/10
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/5'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/3
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/2
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/7'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/12
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/1'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/6'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/8'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/10'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/5
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/2'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/3'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile/11'
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/4
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/7
[VER] [sqli-error-based] Sent HTTP request to http://localhost:8082/profile'/9
[VER] [sqli-error-based] Skipped /profile from parameter for http://localhost:8082/profile"/9 as found uninteresting 10 times
```

With input
```
http://localhost:8082/profile/1
http://localhost:8082/profile/2
http://localhost:8082/profile/3
http://localhost:8082/profile/4
http://localhost:8082/profile/5
http://localhost:8082/profile/6
http://localhost:8082/profile/7
http://localhost:8082/profile/8
http://localhost:8082/profile/9
http://localhost:8082/profile/10
http://localhost:8082/profile/11
http://localhost:8082/profile/12
http://localhost:8082/profile/12
```

2024-05-07 14:03 UTC, Ice3man543 commented
- Added configurable aggression level to fuzzing payloads with `fuzz-aggression` flag
 
```yaml
linux_path:
  low:
    - /etc/passwd
  medium:
    - ../etc/passwd
    - ../../etc/passwd
  high:
    - ../../../etc/passwd
    - ../../../../etc/passwd
    - ../../../../../etc/passwd`
```

Three agression are supported -
  - low
  - medium
  - high
low is the default level which is fairly quick. If medium is specified, all templates from
low and medium are executed. Similarly with high, including all templates
from low, medium, high.

2024-05-08 07:09 UTC, Mzack9999 approved these changes

2024-05-21 13:18 UTC, tarunKoyalwar approved these changes

2024-06-10 23:13 UTC, ehsandeep approved these changes

2024-06-10 23:13 UTC, merged