introduce timeout variants
projectdiscovery/nuclei pull request #5228
Opened 2024-05-27 09:54 UTC by dogancanbakir

## Proposed changes

Closes #5214

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-06-07 10:28 UTC, dogancanbakir commented on pkg/types/types.go
> +}
Might be missing something here, but the default is already 10 seconds. What do you mean by validating `options.Timeout`?

2024-06-13 13:35 UTC, tarunKoyalwar commented on pkg/types/types.go
> +}
yes, it is 10seconds but when using sdk or internals ( which we do) there might be a possibility of Timeout being set to 0 . if i am not wrong we handle this explicitly in fastdialer or retryablehttp , thought we should do the same here

2024-06-13 13:36 UTC, tarunKoyalwar requested changes
changes + merge conflict + test failure

2024-07-08 12:00 UTC, tarunKoyalwar approved these changes
lgtm !

now all timeouts are stored in `Timeouts` struct which is pluggable ( not required and derived from -timeout but can manually be specified via SDK for more control ) .

All Known Timeouts and their default values
```go
// Timeouts is a struct that contains all the timeout variants for nuclei
// dialer timeout is used to derive other timeouts
type Timeouts struct {
	// DialTimeout for fastdialer (default 10s)
	DialTimeout time.Duration
	// Tcp(Network Protocol) Read From Connection Timeout (default 5s)
	TcpReadTimeout time.Duration
	// Http Response Header Timeout (default 10s)
	// this timeout prevents infinite hangs started by server if any
	// this is temporarily overridden when using @timeout request annotation
	HttpResponseHeaderTimeout time.Duration
	// HttpTimeout for http client (default -> 3 x dial-timeout = 30s)
	HttpTimeout time.Duration
	// JsCompilerExec timeout/deadline (default -> 2 x dial-timeout = 20s)
	JsCompilerExecutionTimeout time.Duration
	// CodeExecutionTimeout for code execution (default -> 3 x dial-timeout = 30s)
	CodeExecutionTimeout time.Duration
}
```

>[!CAUTION]
> This change removes below cli flags
> ```console
>  -dt, -dialer-timeout value  timeout for network requests.
>  -rrt, -response-read-timeout value  response read timeout in seconds (default 5s)
> ```

2024-07-15 10:27 UTC, ehsandeep approved these changes

2024-07-15 10:27 UTC, merged