Fix `ExecuteCallbackWithCtx` to use the context that was provided
projectdiscovery/nuclei pull request #5236
Opened 2024-05-28 20:54 UTC by doug-threatmate

This updates `ExecuteCallbackWithCtx` to use the context that was provided.

## Proposed changes

Recently, context support was added in various places in Nuclei.  In particular, `ExecuteCallbackWithCtx` was added to replace `ExecuteCallback`.  However, the context that is passed in to `ExecuteCallbackWithCtx` is unused.

This change passes that context along to `ExecuteScanWithOpts` instead of using `context.Background()`.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-05-28 21:01 UTC, stan-threatmate commented
@tarunKoyalwar this is needed to allow for context cancellation through the SDK.

2024-05-29 09:12 UTC, GeorginaReeder commented
Thanks so much for your contribution @doug-threatmate , we appreciate it!

2024-05-29 14:09 UTC, tarunKoyalwar requested changes
thanks for PR and looks like i missed this , after taking a closer look , it seems like there are more hardcoded context especially when creating new RateLimiter in library, i fixed this in this branch but i am getting 403 when i push changes

@doug-threatmate @stan-threatmate , can you give push access to this PR/branch https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2024-05-29 19:30 UTC, doug-threatmate commented
@tarunKoyalwar I don't have the button that your guide references, but I did invite you to the repo, so maybe that'll do the same thing.

2024-05-30 10:14 UTC, tarunKoyalwar approved these changes
lgtm !

sorry about the delay , but i have removed all hardcoded contexts in library, this required a change in two public facing functions 

```go
NewThreadSafeNucleiEngine(opts ..)
NewNucleiEngine(opts ...)
```
both of them are now marked as deprecated in favour of

```go
NewThreadSafeNucleiEngineCtx(ctx context.Context,opts ..)
NewNucleiEngineCtx(ctx context.Context, opts ...)
```

the earlier ones will still work but using those functions is not recommended because if context is cancelled it might cause goroutine leaks

2024-05-30 10:34 UTC, ehsandeep approved these changes

2024-05-30 10:34 UTC, merged