fix: types.RequestResponse url field UnmarshalJSON bug
projectdiscovery/nuclei pull request #5267
Opened 2024-06-06 03:35 UTC by LazyMaple

## Proposed changes

In Go, when you use map[string]json.RawMessage to parse JSON data, the fields retain their original JSON-encoded format. json.RawMessage is essentially a []byte that contains the raw encoded JSON data. This means that if the JSON field is a string, it will include the quotation marks (").
Here’s a quick example to illustrate the situation:

```
package main

import (
    "encoding/json"
    "fmt"
)

func main() {
    data := `{"url": "testphp.vulnweb.com"}`

    var m map[string]json.RawMessage
    err := json.Unmarshal([]byte(data), &m)
    if err != nil {
        fmt.Println(err)
        return
    }

    // Printing the raw message byte array
    fmt.Printf("RawMessage in bytes: %v\n", m["url"])

    // Decode the "url" field
    var url string
    err = json.Unmarshal(m["url"], &url)
    if err != nil {
        fmt.Println(err)
        return
    }

    fmt.Printf("Original RawMessage: %s\n", string(m["url"]))
    fmt.Printf("Parsed URL: %s\n", url)
}
```
When you run this program, the output will be:

```
RawMessage in bytes: [34 116 101 115 116 112 104 112 46 118 117 108 110 119 101 98 46 99 111 109 34]
Original RawMessage: "testphp.vulnweb.com"
Parsed URL: testphp.vulnweb.com
```

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-06-06 10:03 UTC, GeorginaReeder commented
Thanks for your contribution @LazyMaple , we appreciate it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

2024-06-06 13:35 UTC, dogancanbakir requested changes

2024-06-06 13:35 UTC, dogancanbakir commented on pkg/input/types/http_test.go
> +			err := json.Unmarshal([]byte(tc.rawJSONStr), &rr)
Can we test `func (rr *RequestResponse) UnmarshalJSON(data []byte) error {}` instead?

2024-06-07 10:02 UTC, dogancanbakir requested changes

2024-06-07 16:48 UTC, LazyMaple commented on pkg/input/types/http_test.go
> +			err := rr.UnmarshalJSON([]byte(tc.rawJSONStr))
ok

2024-06-08 06:24 UTC, dogancanbakir approved these changes

2024-06-15 22:35 UTC, merged