feat: upload existing scan results
projectdiscovery/nuclei pull request #5603
Opened 2024-09-05 04:12 UTC by RamanaReddy0M

## Proposed changes

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2024-09-05 08:16 UTC, dogancanbakir approved these changes
```console
$ go run . -pdu result.jsonl -sname 'pdcp-upload-test'

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.2

                projectdiscovery.io

[INF] Uploading scan results to cloud dashboard from result.jsonl
[INF] 3 Scan results uploaded to cloud, you can view scan results at https://cloud.projectdiscovery.io/scans/crcmh0todknc73bvbm20?team_id=none
```

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/cc6e358e-41dd-4b2f-85e7-411aacd335e3">

2024-09-07 12:32 UTC, tarunKoyalwar requested changes
team id env value not used https://github.com/projectdiscovery/nuclei/blob/2b5a8f5b63cded0019a1c54764f215dc422e45df/internal/pdcp/writer.go#L38-L43

apart from that everything else lgtm !

2024-09-10 04:47 UTC, RamanaReddy0M commented
> team id env value not used
> 
> https://github.com/projectdiscovery/nuclei/blob/2b5a8f5b63cded0019a1c54764f215dc422e45df/internal/pdcp/writer.go#L38-L43
> 
> apart from that everything else lgtm !

We are using [here](https://github.com/projectdiscovery/nuclei/pull/5603/files#diff-59fb62b084629887445a914e9e8cbbef5e240247bc36f282b28ed8d530df2387L422)!

2024-09-12 10:43 UTC, ehsandeep approved these changes

2024-09-12 10:43 UTC, merged