handle env variables in dynamic secret file
projectdiscovery/nuclei pull request #5835
Opened 2024-11-18 14:07 UTC by alban-stourbe-wmx

## Proposed changes
Add env variables  in dynamic secret files. 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2024-11-20 09:42 UTC, dogancanbakir requested changes

2024-11-20 09:42 UTC, dogancanbakir commented on internal/runner/lazy.go
> +			if strings.HasPrefix(v.Value, "$") {
we can use https://github.com/projectdiscovery/utils/blob/main/env/env.go#L17

2024-11-20 12:23 UTC, tarunKoyalwar approved these changes
lgtm ! 

along with env secrets now secrets can also be specified from -v and -env-vars ex:

### Env based secret
```yaml
variables:
   - key: password
     value: $PASSWORD
```

### Config file based secrets ( using -env-vars or -vars )
```yaml
variables:
     - key: password
     - value: {{password}}
```

2024-11-21 09:27 UTC, alban-stourbe-wmx commented
> * needs rebase from dev

Hi @tarunKoyalwar, the rebase has been made. Thank for the code added ☝️

2024-11-21 11:03 UTC, ehsandeep approved these changes
Thank you @alban-stourbe-wmx for this update, FYI we are also working on https://github.com/projectdiscovery/nuclei/pull/5841

2024-11-21 11:04 UTC, merged

2024-11-21 11:08 UTC, alban-stourbe-wmx commented
> Thank you @alban-stourbe-wmx for this update, FYI we are also working on #5841

Thanks to you and also congrats to @dwisiswant0 and @tarunKoyalwar