Support Raw Base64 Encoding for Deserialization Helpers
projectdiscovery/nuclei pull request #994
Opened 2021-09-01 17:13 UTC by wdahlenburg

For https://github.com/projectdiscovery/nuclei-templates/pull/2540, I have noticed issues where the default base64 and url-encoding (urlsafeBase64Encode method) will break the deserialization gadget.

This PR adds a small helper to support raw base64 encoding. It does not perform the url encoding like the default option.

I'd like to say this is an issue with padding in the deserialization payloads. This helper appears to create more reliable results for CVE-2015-7450.

This will impact the following template: https://github.com/projectdiscovery/nuclei-templates/blob/master/iot/qvisdvr-deserialization-rce.yaml. Ideally that template could be re-verified with this PR, but otherwise the helper used could be changed to `"base64-url"` or similar. Alternatively this PR be changed to modify `"base64"` to `"base64-raw"`.

2021-09-02 12:07 UTC, Ice3man543 approved these changes

2021-09-02 12:26 UTC, ehsandeep requested changes

2021-09-02 12:26 UTC, ehsandeep commented on v2/pkg/protocols/common/helpers/deserialization/java.go
> +	case "base64":
Can you update the name from `base64` to `base64-raw`

2021-09-03 06:44 UTC, ehsandeep approved these changes

2021-09-03 06:44 UTC, merged